// i18n.js — переключение языка интерфейса и хранение выбора в localStorage

/* ---------- Список поддерживаемых языков ----------
   "Все языки" в буквальном смысле (тысячи) нереалистично
   поддерживать вручную, поэтому здесь — курируемый набор
   основных мировых языков. Массив LANGUAGES — единственное
   место, куда нужно добавить новый язык (плюс перевод ключей
   в объекте I18N ниже), чтобы расширить список. */
const LANGUAGES = [
  { code: "en", name: "English" },
  { code: "ru", name: "Русский" },
  { code: "es", name: "Español" },
  { code: "fr", name: "Français" },
  { code: "de", name: "Deutsch" },
  { code: "it", name: "Italiano" },
  { code: "pt", name: "Português" },
  { code: "zh", name: "中文" },
  { code: "ja", name: "日本語" },
  { code: "ko", name: "한국어" },
  { code: "ar", name: "العربية" },
  { code: "hi", name: "हिन्दी" },
  { code: "tr", name: "Türkçe" },
  { code: "pl", name: "Polski" },
  { code: "nl", name: "Nederlands" },
  { code: "uk", name: "Українська" },
  { code: "vi", name: "Tiếng Việt" },
  { code: "th", name: "ไทย" },
  { code: "id", name: "Bahasa Indonesia" },
  { code: "sv", name: "Svenska" },
];

const RTL_LANGS = new Set(["ar"]);

const I18N = {
  nav_picker: {
    en: "Picker",
    ru: "Пикер",
    es: "Selector",
    fr: "Sélecteur",
    de: "Auswahl",
    it: "Selettore",
    pt: "Seletor",
    zh: "拾色器",
    ja: "ピッカー",
    ko: "피커",
    ar: "المنتقي",
    hi: "पिकर",
    tr: "Seçici",
    pl: "Wybór",
    nl: "Kiezer",
    uk: "Піпетка",
    vi: "Bộ chọn",
    th: "ตัวเลือกสี",
    id: "Pemilih",
    sv: "Väljare",
  },
  nav_image: {
    en: "Image",
    ru: "Изображение",
    es: "Imagen",
    fr: "Image",
    de: "Bild",
    it: "Immagine",
    pt: "Imagem",
    zh: "图片",
    ja: "画像",
    ko: "이미지",
    ar: "الصورة",
    hi: "छवि",
    tr: "Görsel",
    pl: "Obraz",
    nl: "Afbeelding",
    uk: "Зображення",
    vi: "Hình ảnh",
    th: "รูปภาพ",
    id: "Gambar",
    sv: "Bild",
  },
  nav_palette: {
    en: "Palette",
    ru: "Палитра",
    es: "Paleta",
    fr: "Palette",
    de: "Palette",
    it: "Tavolozza",
    pt: "Paleta",
    zh: "调色板",
    ja: "パレット",
    ko: "팔레트",
    ar: "اللوحة",
    hi: "पैलेट",
    tr: "Palet",
    pl: "Paleta",
    nl: "Palet",
    uk: "Палітра",
    vi: "Bảng màu",
    th: "จานสี",
    id: "Palet",
    sv: "Palett",
  },
  nav_converter: {
    en: "Converter",
    ru: "Конвертер",
    es: "Conversor",
    fr: "Convertisseur",
    de: "Konverter",
    it: "Convertitore",
    pt: "Conversor",
    zh: "转换器",
    ja: "コンバーター",
    ko: "변환기",
    ar: "المحوّل",
    hi: "परिवर्तक",
    tr: "Dönüştürücü",
    pl: "Konwerter",
    nl: "Converter",
    uk: "Конвертер",
    vi: "Bộ chuyển đổi",
    th: "ตัวแปลง",
    id: "Pengonversi",
    sv: "Omvandlare",
  },
  nav_library: {
    en: "Library",
    ru: "Библиотека",
    es: "Biblioteca",
    fr: "Bibliothèque",
    de: "Bibliothek",
    it: "Libreria",
    pt: "Biblioteca",
    zh: "库",
    ja: "ライブラリ",
    ko: "라이브러리",
    ar: "المكتبة",
    hi: "लाइब्रेरी",
    tr: "Kütüphane",
    pl: "Biblioteka",
    nl: "Bibliotheek",
    uk: "Бібліотека",
    vi: "Thư viện",
    th: "คลัง",
    id: "Pustaka",
    sv: "Bibliotek",
  },
  nav_accessibility: {
    en: "Accessibility",
    ru: "Доступность",
    es: "Accesibilidad",
    fr: "Accessibilité",
    de: "Barrierefreiheit",
    it: "Accessibilità",
    pt: "Acessibilidade",
    zh: "无障碍",
    ja: "アクセシビリティ",
    ko: "접근성",
    ar: "إمكانية الوصول",
    hi: "सुगम्यता",
    tr: "Erişilebilirlik",
    pl: "Dostępność",
    nl: "Toegankelijkheid",
    uk: "Доступність",
    vi: "Trợ năng",
    th: "การเข้าถึง",
    id: "Aksesibilitas",
    sv: "Tillgänglighet",
  },
  nav_resources: {
    en: "Resources",
    ru: "Ресурсы",
    es: "Recursos",
    fr: "Ressources",
    de: "Ressourcen",
    it: "Risorse",
    pt: "Recursos",
    zh: "资源",
    ja: "リソース",
    ko: "리소스",
    ar: "الموارد",
    hi: "संसाधन",
    tr: "Kaynaklar",
    pl: "Zasoby",
    nl: "Bronnen",
    uk: "Ресурси",
    vi: "Tài nguyên",
    th: "แหล่งข้อมูล",
    id: "Sumber Daya",
    sv: "Resurser",
  },
  nav_more: {
    en: "More",
    ru: "Ещё",
    es: "Más",
    fr: "Plus",
    de: "Mehr",
    it: "Altro",
    pt: "Mais",
    zh: "更多",
    ja: "その他",
    ko: "더보기",
    ar: "المزيد",
    hi: "अधिक",
    tr: "Diğer",
    pl: "Więcej",
    nl: "Meer",
    uk: "Ще",
    vi: "Thêm",
    th: "เพิ่มเติม",
    id: "Lainnya",
    sv: "Mer",
  },
  quick_colors: {
    en: "Quick Colors",
    ru: "Быстрый выбор",
    es: "Colores rápidos",
    fr: "Couleurs rapides",
    de: "Schnellfarben",
    it: "Colori rapidi",
    pt: "Cores rápidas",
    zh: "快速颜色",
    ja: "クイックカラー",
    ko: "빠른 색상",
    ar: "ألوان سريعة",
    hi: "त्वरित रंग",
    tr: "Hızlı Renkler",
    pl: "Szybkie kolory",
    nl: "Snelle kleuren",
    uk: "Швидкі кольори",
    vi: "Màu nhanh",
    th: "สีด่วน",
    id: "Warna Cepat",
    sv: "Snabbfärger",
  },

  /* ---------- Страница Library ---------- */
  library_subtitle: {
    en: "Browse curated palettes and a library of named colors",
    ru: "Изучайте готовые палитры и библиотеку именованных цветов",
  },
  library_search_placeholder: {
    en: "Search the library...",
    ru: "Поиск по библиотеке...",
  },
  library_tab_palettes: {
    en: "Palettes",
    ru: "Палитры",
  },
  library_tab_colors: {
    en: "Named Colors",
    ru: "Именованные цвета",
  },
  library_empty: {
    en: "Nothing matches your search.",
    ru: "Ничего не найдено по вашему запросу.",
  },
  library_copy_all: {
    en: "Copy All",
    ru: "Скопировать всё",
  },
  library_save_palette: {
    en: "Save",
    ru: "Сохранить",
  },
  library_saved_toast: {
    en: "Saved to My Palettes",
    ru: "Сохранено в «Мои палитры»",
  },
  library_color_saved: {
    en: "Color saved",
    ru: "Цвет сохранён",
  },
  library_color_removed: {
    en: "Color removed",
    ru: "Цвет удалён",
  },
  library_results_palettes: {
    en: "palettes",
    ru: "палитр",
  },
  library_results_colors: {
    en: "colors",
    ru: "цветов",
  },
  library_category_all: {
    en: "All Categories",
    ru: "Все категории",
  },
  library_category_nature: {
    en: "Nature",
    ru: "Природа",
  },
  library_category_pastel: {
    en: "Pastel",
    ru: "Пастель",
  },
  library_category_vintage: {
    en: "Vintage",
    ru: "Винтаж",
  },
  library_category_neon: {
    en: "Vibrant",
    ru: "Яркие",
  },
  library_category_monochrome: {
    en: "Monochrome",
    ru: "Монохром",
  },
  library_category_seasonal: {
    en: "Seasonal",
    ru: "Сезонные",
  },

  export_label: {
    en: "Export",
    ru: "Экспорт",
    es: "Exportar",
    fr: "Exporter",
    de: "Exportieren",
    it: "Esporta",
    pt: "Exportar",
    zh: "导出",
    ja: "エクスポート",
    ko: "내보내기",
    ar: "تصدير",
    hi: "निर्यात",
    tr: "Dışa Aktar",
    pl: "Eksportuj",
    nl: "Exporteren",
    uk: "Експорт",
    vi: "Xuất",
    th: "ส่งออก",
    id: "Ekspor",
    sv: "Exportera",
  },
  menu_export_css: {
    en: "Copy CSS variable",
    ru: "Скопировать CSS переменную",
    es: "Copiar variable CSS",
    fr: "Copier la variable CSS",
    de: "CSS-Variable kopieren",
    it: "Copia variabile CSS",
    pt: "Copiar variável CSS",
    zh: "复制 CSS 变量",
    ja: "CSS変数をコピー",
    ko: "CSS 변수 복사",
    ar: "نسخ متغير CSS",
    hi: "CSS वेरिएबल कॉपी करें",
    tr: "CSS değişkenini kopyala",
    pl: "Kopiuj zmienną CSS",
    nl: "CSS-variabele kopiëren",
    uk: "Копіювати CSS-змінну",
    vi: "Sao chép biến CSS",
    th: "คัดลอกตัวแปร CSS",
    id: "Salin variabel CSS",
    sv: "Kopiera CSS-variabel",
  },
  menu_export_json: {
    en: "Download JSON",
    ru: "Скачать JSON",
    es: "Descargar JSON",
    fr: "Télécharger JSON",
    de: "JSON herunterladen",
    it: "Scarica JSON",
    pt: "Baixar JSON",
    zh: "下载 JSON",
    ja: "JSONをダウンロード",
    ko: "JSON 다운로드",
    ar: "تنزيل JSON",
    hi: "JSON डाउनलोड करें",
    tr: "JSON indir",
    pl: "Pobierz JSON",
    nl: "JSON downloaden",
    uk: "Завантажити JSON",
    vi: "Tải JSON",
    th: "ดาวน์โหลด JSON",
    id: "Unduh JSON",
    sv: "Ladda ner JSON",
  },
  menu_export_png: {
    en: "Download PNG",
    ru: "Скачать PNG",
    es: "Descargar PNG",
    fr: "Télécharger PNG",
    de: "PNG herunterladen",
    it: "Scarica PNG",
    pt: "Baixar PNG",
    zh: "下载 PNG",
    ja: "PNGをダウンロード",
    ko: "PNG 다운로드",
    ar: "تنزيل PNG",
    hi: "PNG डाउनलोड करें",
    tr: "PNG indir",
    pl: "Pobierz PNG",
    nl: "PNG downloaden",
    uk: "Завантажити PNG",
    vi: "Tải PNG",
    th: "ดาวน์โหลด PNG",
    id: "Unduh PNG",
    sv: "Ladda ner PNG",
  },

  hero_subtitle: {
    en: "Choose, preview, and create beautiful colors easily",
    ru: "Выбирайте, просматривайте и создавайте красивые цвета легко",
    es: "Elige, previsualiza y crea colores hermosos fácilmente",
    fr: "Choisissez, prévisualisez et créez de superbes couleurs facilement",
    de: "Wählen, ansehen und wunderschöne Farben ganz einfach erstellen",
    it: "Scegli, visualizza in anteprima e crea colori bellissimi facilmente",
    pt: "Escolha, visualize e crie cores lindas com facilidade",
    zh: "轻松挑选、预览并创建漂亮的颜色",
    ja: "美しい色を簡単に選んで、プレビューして、作成しましょう",
    ko: "아름다운 색상을 쉽게 선택하고 미리 보고 만들어보세요",
    ar: "اختر وعاين وأنشئ ألوانًا جميلة بسهولة",
    hi: "सुंदर रंग आसानी से चुनें, देखें और बनाएं",
    tr: "Güzel renkleri kolayca seçin, önizleyin ve oluşturun",
    pl: "Wybieraj, podglądaj i twórz piękne kolory z łatwością",
    nl: "Kies, bekijk en maak eenvoudig prachtige kleuren",
    uk: "Обирайте, переглядайте та створюйте красиві кольори легко",
    vi: "Dễ dàng chọn, xem trước và tạo màu sắc đẹp",
    th: "เลือก ดูตัวอย่าง และสร้างสีสวยงามได้อย่างง่ายดาย",
    id: "Pilih, pratinjau, dan buat warna indah dengan mudah",
    sv: "Välj, förhandsgranska och skapa vackra färger enkelt",
  },

  upload_image: {
    en: "Upload Image",
    ru: "Загрузить изображение",
    es: "Subir imagen",
    fr: "Importer une image",
    de: "Bild hochladen",
    it: "Carica immagine",
    pt: "Enviar imagem",
    zh: "上传图片",
    ja: "画像をアップロード",
    ko: "이미지 업로드",
    ar: "تحميل صورة",
    hi: "छवि अपलोड करें",
    tr: "Görsel yükle",
    pl: "Prześlij obraz",
    nl: "Afbeelding uploaden",
    uk: "Завантажити зображення",
    vi: "Tải ảnh lên",
    th: "อัปโหลดรูปภาพ",
    id: "Unggah gambar",
    sv: "Ladda upp bild",
  },
  saved_colors: {
    en: "Saved Colors",
    ru: "Сохранённые цвета",
    es: "Colores guardados",
    fr: "Couleurs enregistrées",
    de: "Gespeicherte Farben",
    it: "Colori salvati",
    pt: "Cores salvas",
    zh: "已保存的颜色",
    ja: "保存した色",
    ko: "저장된 색상",
    ar: "الألوان المحفوظة",
    hi: "सहेजे गए रंग",
    tr: "Kaydedilen renkler",
    pl: "Zapisane kolory",
    nl: "Opgeslagen kleuren",
    uk: "Збережені кольори",
    vi: "Màu đã lưu",
    th: "สีที่บันทึกไว้",
    id: "Warna tersimpan",
    sv: "Sparade färger",
  },

  card1_title: {
    en: "1. Pick a Color",
    ru: "1. Выберите цвет",
    es: "1. Elige un color",
    fr: "1. Choisir une couleur",
    de: "1. Farbe wählen",
    it: "1. Scegli un colore",
    pt: "1. Escolha uma cor",
    zh: "1. 选择颜色",
    ja: "1. 色を選ぶ",
    ko: "1. 색상 선택",
    ar: "1. اختر لونًا",
    hi: "1. रंग चुनें",
    tr: "1. Bir Renk Seç",
    pl: "1. Wybierz kolor",
    nl: "1. Kies een kleur",
    uk: "1. Виберіть колір",
    vi: "1. Chọn màu",
    th: "1. เลือกสี",
    id: "1. Pilih Warna",
    sv: "1. Välj en färg",
  },
  card1_sub: {
    en: "Choose your perfect color",
    ru: "Выберите идеальный цвет",
    es: "Elige tu color perfecto",
    fr: "Choisissez votre couleur idéale",
    de: "Wählen Sie Ihre perfekte Farbe",
    it: "Scegli il tuo colore perfetto",
    pt: "Escolha sua cor perfeita",
    zh: "选择你的完美颜色",
    ja: "あなたにぴったりの色を選びましょう",
    ko: "완벽한 색상을 선택하세요",
    ar: "اختر لونك المثالي",
    hi: "अपना उपयुक्त रंग चुनें",
    tr: "Mükemmel renginizi seçin",
    pl: "Wybierz idealny kolor",
    nl: "Kies je perfecte kleur",
    uk: "Виберіть ідеальний колір",
    vi: "Chọn màu hoàn hảo của bạn",
    th: "เลือกสีที่สมบูรณ์แบบของคุณ",
    id: "Pilih warna sempurna Anda",
    sv: "Välj din perfekta färg",
  },
  tab_wheel: {
    en: "Wheel",
    ru: "Круг",
    es: "Rueda",
    fr: "Roue",
    de: "Farbrad",
    it: "Ruota",
    pt: "Roda",
    zh: "色轮",
    ja: "ホイール",
    ko: "휠",
    ar: "العجلة",
    hi: "व्हील",
    tr: "Çark",
    pl: "Koło",
    nl: "Wiel",
    uk: "Коло",
    vi: "Vòng tròn",
    th: "วงล้อ",
    id: "Roda",
    sv: "Hjul",
  },
  tab_sliders: {
    en: "Sliders",
    ru: "Ползунки",
    es: "Deslizadores",
    fr: "Curseurs",
    de: "Regler",
    it: "Cursori",
    pt: "Deslizadores",
    zh: "滑块",
    ja: "スライダー",
    ko: "슬라이더",
    ar: "أشرطة التمرير",
    hi: "स्लाइडर",
    tr: "Kaydırıcılar",
    pl: "Suwaki",
    nl: "Schuifregelaars",
    uk: "Повзунки",
    vi: "Thanh trượt",
    th: "แถบเลื่อน",
    id: "Penggeser",
    sv: "Reglage",
  },
  label_hue: {
    en: "Hue",
    ru: "Оттенок",
  },
  label_saturation: {
    en: "Saturation",
    ru: "Насыщенность",
    es: "Saturación",
    fr: "Saturation",
    de: "Sättigung",
    it: "Saturazione",
    pt: "Saturação",
    zh: "饱和度",
    ja: "彩度",
    ko: "채도",
    ar: "التشبع",
    hi: "संतृप्ति",
    tr: "Doygunluk",
    pl: "Nasycenie",
    nl: "Verzadiging",
    uk: "Насиченість",
    vi: "Độ bão hòa",
    th: "ความอิ่มตัว",
    id: "Saturasi",
    sv: "Mättnad",
  },
  label_lightness: {
    en: "Lightness",
    ru: "Светлота",
    es: "Luminosidad",
    fr: "Luminosité",
    de: "Helligkeit",
    it: "Luminosità",
    pt: "Luminosidade",
    zh: "明度",
    ja: "明度",
    ko: "명도",
    ar: "الإضاءة",
    hi: "चमक",
    tr: "Parlaklık",
    pl: "Jasność",
    nl: "Lichtheid",
    uk: "Світлість",
    vi: "Độ sáng",
    th: "ความสว่าง",
    id: "Kecerahan",
    sv: "Ljushet",
  },
  label_alpha: {
    en: "Alpha",
    ru: "Альфа",
    es: "Alfa",
    fr: "Alpha",
    de: "Alpha",
    it: "Alfa",
    pt: "Alfa",
    zh: "透明度",
    ja: "アルファ",
    ko: "알파",
    ar: "ألفا",
    hi: "अल्फा",
    tr: "Alfa",
    pl: "Alfa",
    nl: "Alfa",
    uk: "Альфа",
    vi: "Alpha",
    th: "อัลฟา",
    id: "Alfa",
    sv: "Alfa",
  },
  quick_input: {
    en: "Quick Input",
    ru: "Быстрый ввод",
    es: "Entrada rápida",
    fr: "Saisie rapide",
    de: "Schnelleingabe",
    it: "Inserimento rapido",
    pt: "Entrada rápida",
    zh: "快速输入",
    ja: "クイック入力",
    ko: "빠른 입력",
    ar: "إدخال سريع",
    hi: "त्वरित इनपुट",
    tr: "Hızlı Giriş",
    pl: "Szybkie wprowadzanie",
    nl: "Snelle invoer",
    uk: "Швидке введення",
    vi: "Nhập nhanh",
    th: "ป้อนข้อมูลด่วน",
    id: "Input Cepat",
    sv: "Snabb inmatning",
  },
  recent_colors: {
    en: "Recent Colors",
    ru: "Недавние цвета",
    es: "Colores recientes",
    fr: "Couleurs récentes",
    de: "Zuletzt verwendet",
    it: "Colori recenti",
    pt: "Cores recentes",
    zh: "最近使用的颜色",
    ja: "最近使った色",
    ko: "최근 색상",
    ar: "الألوان الأخيرة",
    hi: "हाल के रंग",
    tr: "Son Renkler",
    pl: "Ostatnie kolory",
    nl: "Recente kleuren",
    uk: "Останні кольори",
    vi: "Màu gần đây",
    th: "สีล่าสุด",
    id: "Warna Terbaru",
    sv: "Senaste färger",
  },
  clear: {
    en: "Clear",
    ru: "Очистить",
    es: "Borrar",
    fr: "Effacer",
    de: "Löschen",
    it: "Cancella",
    pt: "Limpar",
    zh: "清除",
    ja: "クリア",
    ko: "지우기",
    ar: "مسح",
    hi: "साफ़ करें",
    tr: "Temizle",
    pl: "Wyczyść",
    nl: "Wissen",
    uk: "Очистити",
    vi: "Xóa",
    th: "ล้าง",
    id: "Hapus",
    sv: "Rensa",
  },

  card2_title: {
    en: "2. Selected Color",
    ru: "2. Выбранный цвет",
    es: "2. Color seleccionado",
    fr: "2. Couleur sélectionnée",
    de: "2. Ausgewählte Farbe",
    it: "2. Colore selezionato",
    pt: "2. Cor selecionada",
    zh: "2. 已选颜色",
    ja: "2. 選択した色",
    ko: "2. 선택한 색상",
    ar: "2. اللون المحدد",
    hi: "2. चयनित रंग",
    tr: "2. Seçilen Renk",
    pl: "2. Wybrany kolor",
    nl: "2. Geselecteerde kleur",
    uk: "2. Вибраний колір",
    vi: "2. Màu đã chọn",
    th: "2. สีที่เลือก",
    id: "2. Warna Terpilih",
    sv: "2. Vald färg",
  },
  card2_sub: {
    en: "Preview and copy your color values",
    ru: "Просмотрите и скопируйте значения цвета",
    es: "Previsualiza y copia los valores de tu color",
    fr: "Prévisualisez et copiez les valeurs de votre couleur",
    de: "Vorschau und Kopieren Ihrer Farbwerte",
    it: "Visualizza in anteprima e copia i valori del colore",
    pt: "Visualize e copie os valores da sua cor",
    zh: "预览并复制颜色值",
    ja: "色の値をプレビューしてコピー",
    ko: "색상 값을 미리 보고 복사하세요",
    ar: "عاين وانسخ قيم لونك",
    hi: "अपने रंग मान देखें और कॉपी करें",
    tr: "Renk değerlerinizi önizleyin ve kopyalayın",
    pl: "Podgląd i kopiowanie wartości koloru",
    nl: "Bekijk en kopieer je kleurwaarden",
    uk: "Перегляньте та скопіюйте значення кольору",
    vi: "Xem trước và sao chép giá trị màu",
    th: "ดูตัวอย่างและคัดลอกค่าสีของคุณ",
    id: "Pratinjau dan salin nilai warna Anda",
    sv: "Förhandsgranska och kopiera dina färgvärden",
  },
  harmony_label: {
    en: "Color Harmony",
    ru: "Гармония цвета",
    es: "Armonía de color",
    fr: "Harmonie des couleurs",
    de: "Farbharmonie",
    it: "Armonia dei colori",
    pt: "Harmonia de cores",
    zh: "色彩和谐",
    ja: "カラーハーモニー",
    ko: "색상 조화",
    ar: "توافق الألوان",
    hi: "रंग सामंजस्य",
    tr: "Renk Uyumu",
    pl: "Harmonia kolorów",
    nl: "Kleurharmonie",
    uk: "Гармонія кольорів",
    vi: "Hòa sắc",
    th: "ความกลมกลืนของสี",
    id: "Harmoni Warna",
    sv: "Färgharmoni",
  },
  badge_new: {
    en: "New",
    ru: "Новое",
    es: "Nuevo",
    fr: "Nouveau",
    de: "Neu",
    it: "Nuovo",
    pt: "Novo",
    zh: "新",
    ja: "新機能",
    ko: "신규",
    ar: "جديد",
    hi: "नया",
    tr: "Yeni",
    pl: "Nowość",
    nl: "Nieuw",
    uk: "Нове",
    vi: "Mới",
    th: "ใหม่",
    id: "Baru",
    sv: "Nytt",
  },
  copy_all: {
    en: "Copy All Values",
    ru: "Скопировать все значения",
    es: "Copiar todos los valores",
    fr: "Copier toutes les valeurs",
    de: "Alle Werte kopieren",
    it: "Copia tutti i valori",
    pt: "Copiar todos os valores",
    zh: "复制所有数值",
    ja: "すべての値をコピー",
    ko: "모든 값 복사",
    ar: "نسخ جميع القيم",
    hi: "सभी मान कॉपी करें",
    tr: "Tüm Değerleri Kopyala",
    pl: "Kopiuj wszystkie wartości",
    nl: "Alle waarden kopiëren",
    uk: "Скопіювати всі значення",
    vi: "Sao chép tất cả giá trị",
    th: "คัดลอกค่าทั้งหมด",
    id: "Salin Semua Nilai",
    sv: "Kopiera alla värden",
  },

  card3_title: {
    en: "3. Shades, Tints & Tones",
    ru: "3. Оттенки, тона и тени",
    es: "3. Sombras, tintes y tonos",
    fr: "3. Nuances, teintes et tons",
    de: "3. Schattierungen, Aufhellungen & Töne",
    it: "3. Ombre, tinte e toni",
    pt: "3. Sombras, tons claros e tons",
    zh: "3. 色阶、浅色调与灰色调",
    ja: "3. シェード・ティント・トーン",
    ko: "3. 셰이드, 틴트 & 톤",
    ar: "3. الظلال والتوينت والتوين",
    hi: "3. शेड्स, टिंट्स और टोन",
    tr: "3. Gölgeler, Tonlar ve Tenler",
    pl: "3. Cienie, odcienie i tony",
    nl: "3. Schaduwen, tinten en tonen",
    uk: "3. Відтінки, тони й тонування",
    vi: "3. Sắc độ, sắc thái & tông màu",
    th: "3. เฉด โทนอ่อน และโทนสี",
    id: "3. Bayangan, Rona & Nada",
    sv: "3. Nyanser, toner och skuggor",
  },
  card3_sub: {
    en: "Explore variations of your selected color",
    ru: "Изучите вариации выбранного цвета",
    es: "Explora variaciones de tu color seleccionado",
    fr: "Explorez les variations de votre couleur sélectionnée",
    de: "Entdecken Sie Variationen Ihrer ausgewählten Farbe",
    it: "Esplora le varianti del colore selezionato",
    pt: "Explore variações da cor selecionada",
    zh: "探索所选颜色的变化",
    ja: "選択した色のバリエーションを見る",
    ko: "선택한 색상의 다양한 변형을 살펴보세요",
    ar: "استكشف تنويعات لونك المحدد",
    hi: "अपने चयनित रंग की विविधताएं देखें",
    tr: "Seçilen renginizin varyasyonlarını keşfedin",
    pl: "Poznaj warianty wybranego koloru",
    nl: "Ontdek variaties van je gekozen kleur",
    uk: "Досліджуйте варіації вибраного кольору",
    vi: "Khám phá các biến thể của màu đã chọn",
    th: "สำรวจความหลากหลายของสีที่คุณเลือก",
    id: "Jelajahi variasi warna pilihan Anda",
    sv: "Utforska variationer av din valda färg",
  },
  tab_shades: {
    en: "Shades",
    ru: "Оттенки",
    es: "Sombras",
    fr: "Nuances",
    de: "Schattierungen",
    it: "Ombre",
    pt: "Sombras",
    zh: "色阶",
    ja: "シェード",
    ko: "셰이드",
    ar: "الظلال",
    hi: "शेड्स",
    tr: "Gölgeler",
    pl: "Cienie",
    nl: "Schaduwen",
    uk: "Відтінки",
    vi: "Sắc độ",
    th: "เฉดสี",
    id: "Bayangan",
    sv: "Nyanser",
  },
  tab_tints: {
    en: "Tints",
    ru: "Тона",
    es: "Tintes",
    fr: "Teintes",
    de: "Aufhellungen",
    it: "Tinte",
    pt: "Tons claros",
    zh: "浅色调",
    ja: "ティント",
    ko: "틴트",
    ar: "توينت",
    hi: "टिंट्स",
    tr: "Tonlar",
    pl: "Odcienie",
    nl: "Tinten",
    uk: "Тони",
    vi: "Sắc thái",
    th: "โทนอ่อน",
    id: "Rona",
    sv: "Toner",
  },
  tab_tones: {
    en: "Tones",
    ru: "Тени",
    es: "Tonos",
    fr: "Tons",
    de: "Töne",
    it: "Toni",
    pt: "Tons",
    zh: "灰色调",
    ja: "トーン",
    ko: "톤",
    ar: "التوين",
    hi: "टोन",
    tr: "Tenler",
    pl: "Tony",
    nl: "Tonen",
    uk: "Тонування",
    vi: "Tông màu",
    th: "โทนสี",
    id: "Nada",
    sv: "Skuggor",
  },
  generate_palette: {
    en: "Generate Palette",
    ru: "Сгенерировать палитру",
    es: "Generar paleta",
    fr: "Générer une palette",
    de: "Palette generieren",
    it: "Genera tavolozza",
    pt: "Gerar paleta",
    zh: "生成调色板",
    ja: "パレットを生成",
    ko: "팔레트 생성",
    ar: "إنشاء لوحة",
    hi: "पैलेट बनाएं",
    tr: "Palet Oluştur",
    pl: "Generuj paletę",
    nl: "Palet genereren",
    uk: "Згенерувати палітру",
    vi: "Tạo bảng màu",
    th: "สร้างจานสี",
    id: "Buat Palet",
    sv: "Generera palett",
  },
  export_palette: {
    en: "Export Palette",
    ru: "Экспортировать палитру",
    es: "Exportar paleta",
    fr: "Exporter la palette",
    de: "Palette exportieren",
    it: "Esporta tavolozza",
    pt: "Exportar paleta",
    zh: "导出调色板",
    ja: "パレットをエクスポート",
    ko: "팔레트 내보내기",
    ar: "تصدير اللوحة",
    hi: "पैलेट निर्यात करें",
    tr: "Paleti Dışa Aktar",
    pl: "Eksportuj paletę",
    nl: "Palet exporteren",
    uk: "Експортувати палітру",
    vi: "Xuất bảng màu",
    th: "ส่งออกจานสี",
    id: "Ekspor Palet",
    sv: "Exportera palett",
  },

  feat1_title: {
    en: "100% Free",
    ru: "100% бесплатно",
    es: "100% gratis",
    fr: "100% gratuit",
    de: "100 % kostenlos",
    it: "100% gratuito",
    pt: "100% gratuito",
    zh: "100% 免费",
    ja: "100%無料",
    ko: "100% 무료",
    ar: "مجاني 100%",
    hi: "100% मुफ़्त",
    tr: "%100 Ücretsiz",
    pl: "100% za darmo",
    nl: "100% gratis",
    uk: "100% безкоштовно",
    vi: "100% miễn phí",
    th: "ฟรี 100%",
    id: "100% Gratis",
    sv: "100 % gratis",
  },
  feat1_desc: {
    en: "No registration required",
    ru: "Регистрация не требуется",
    es: "No se requiere registro",
    fr: "Aucune inscription requise",
    de: "Keine Registrierung erforderlich",
    it: "Nessuna registrazione richiesta",
    pt: "Sem necessidade de cadastro",
    zh: "无需注册",
    ja: "登録不要",
    ko: "등록 불필요",
    ar: "لا حاجة للتسجيل",
    hi: "पंजीकरण की आवश्यकता नहीं",
    tr: "Kayıt gerekmez",
    pl: "Rejestracja niewymagana",
    nl: "Geen registratie vereist",
    uk: "Реєстрація не потрібна",
    vi: "Không cần đăng ký",
    th: "ไม่ต้องลงทะเบียน",
    id: "Tidak perlu registrasi",
    sv: "Ingen registrering krävs",
  },
  feat2_title: {
    en: "Privacy First",
    ru: "Приватность прежде всего",
    es: "La privacidad primero",
    fr: "La confidentialité avant tout",
    de: "Datenschutz zuerst",
    it: "La privacy prima di tutto",
    pt: "Privacidade em primeiro lugar",
    zh: "隐私优先",
    ja: "プライバシー第一",
    ko: "개인정보 우선",
    ar: "الخصوصية أولاً",
    hi: "गोपनीयता पहले",
    tr: "Önce Gizlilik",
    pl: "Prywatność przede wszystkim",
    nl: "Privacy voorop",
    uk: "Приватність понад усе",
    vi: "Quyền riêng tư là trên hết",
    th: "ความเป็นส่วนตัวมาก่อน",
    id: "Privasi Diutamakan",
    sv: "Integritet först",
  },
  feat2_desc: {
    en: "All processing in your browser",
    ru: "Вся обработка в вашем браузере",
    es: "Todo el procesamiento en tu navegador",
    fr: "Tout le traitement dans votre navigateur",
    de: "Die gesamte Verarbeitung erfolgt in Ihrem Browser",
    it: "Tutta l'elaborazione avviene nel tuo browser",
    pt: "Todo o processamento no seu navegador",
    zh: "所有处理均在浏览器中完成",
    ja: "すべての処理はブラウザ内で行われます",
    ko: "모든 처리가 브라우저에서 이루어집니다",
    ar: "تتم جميع المعالجة داخل متصفحك",
    hi: "सारी प्रोसेसिंग आपके ब्राउज़र में होती है",
    tr: "Tüm işlemler tarayıcınızda gerçekleşir",
    pl: "Całe przetwarzanie odbywa się w Twojej przeglądarce",
    nl: "Alle verwerking gebeurt in je browser",
    uk: "Уся обробка відбувається у вашому браузері",
    vi: "Mọi xử lý đều diễn ra trên trình duyệt của bạn",
    th: "การประมวลผลทั้งหมดอยู่ในเบราว์เซอร์ของคุณ",
    id: "Semua pemrosesan di browser Anda",
    sv: "All bearbetning sker i din webbläsare",
  },
  feat3_title: {
    en: "Export Ready",
    ru: "Готово к экспорту",
    es: "Listo para exportar",
    fr: "Prêt à l'exportation",
    de: "Exportbereit",
    it: "Pronto per l'esportazione",
    pt: "Pronto para exportar",
    zh: "随时导出",
    ja: "エクスポート対応",
    ko: "내보내기 준비 완료",
    ar: "جاهز للتصدير",
    hi: "निर्यात के लिए तैयार",
    tr: "Dışa Aktarmaya Hazır",
    pl: "Gotowe do eksportu",
    nl: "Klaar om te exporteren",
    uk: "Готово до експорту",
    vi: "Sẵn sàng xuất",
    th: "พร้อมส่งออก",
    id: "Siap Diekspor",
    sv: "Klar att exportera",
  },
  feat3_desc: {
    en: "PNG, CSS, JSON formats",
    ru: "Форматы PNG, CSS, JSON",
    es: "Formatos PNG, CSS, JSON",
    fr: "Formats PNG, CSS, JSON",
    de: "PNG-, CSS-, JSON-Formate",
    it: "Formati PNG, CSS, JSON",
    pt: "Formatos PNG, CSS, JSON",
    zh: "PNG、CSS、JSON 格式",
    ja: "PNG、CSS、JSON形式",
    ko: "PNG, CSS, JSON 형식",
    ar: "صيغ PNG وCSS وJSON",
    hi: "PNG, CSS, JSON प्रारूप",
    tr: "PNG, CSS, JSON biçimleri",
    pl: "Formaty PNG, CSS, JSON",
    nl: "PNG-, CSS-, JSON-formaten",
    uk: "Формати PNG, CSS, JSON",
    vi: "Định dạng PNG, CSS, JSON",
    th: "รูปแบบ PNG, CSS, JSON",
    id: "Format PNG, CSS, JSON",
    sv: "PNG-, CSS-, JSON-format",
  },
  feat4_title: {
    en: "WCAG Compliant",
    ru: "Соответствует WCAG",
    es: "Cumple con WCAG",
    fr: "Conforme WCAG",
    de: "WCAG-konform",
    it: "Conforme WCAG",
    pt: "Compatível com WCAG",
    zh: "符合 WCAG 标准",
    ja: "WCAG準拠",
    ko: "WCAG 준수",
    ar: "متوافق مع WCAG",
    hi: "WCAG अनुरूप",
    tr: "WCAG Uyumlu",
    pl: "Zgodność z WCAG",
    nl: "WCAG-conform",
    uk: "Відповідає WCAG",
    vi: "Tuân thủ WCAG",
    th: "เป็นไปตามมาตรฐาน WCAG",
    id: "Sesuai WCAG",
    sv: "WCAG-kompatibel",
  },
  feat4_desc: {
    en: "Accessibility focused",
    ru: "Ориентировано на доступность",
    es: "Enfocado en la accesibilidad",
    fr: "Axé sur l'accessibilité",
    de: "Fokus auf Barrierefreiheit",
    it: "Incentrato sull'accessibilità",
    pt: "Focado em acessibilidade",
    zh: "专注无障碍体验",
    ja: "アクセシビリティ重視",
    ko: "접근성 중심",
    ar: "يركّز على إمكانية الوصول",
    hi: "सुगम्यता पर केंद्रित",
    tr: "Erişilebilirlik odaklı",
    pl: "Skupione na dostępności",
    nl: "Gericht op toegankelijkheid",
    uk: "Орієнтовано на доступність",
    vi: "Chú trọng khả năng tiếp cận",
    th: "มุ่งเน้นการเข้าถึง",
    id: "Berfokus pada aksesibilitas",
    sv: "Fokus på tillgänglighet",
  },
  feat5_title: {
    en: "Works Offline",
    ru: "Работает офлайн",
    es: "Funciona sin conexión",
    fr: "Fonctionne hors ligne",
    de: "Funktioniert offline",
    it: "Funziona offline",
    pt: "Funciona offline",
    zh: "可离线使用",
    ja: "オフラインで動作",
    ko: "오프라인에서 작동",
    ar: "يعمل دون اتصال",
    hi: "ऑफ़लाइन काम करता है",
    tr: "Çevrimdışı Çalışır",
    pl: "Działa offline",
    nl: "Werkt offline",
    uk: "Працює офлайн",
    vi: "Hoạt động ngoại tuyến",
    th: "ใช้งานออฟไลน์ได้",
    id: "Berfungsi Offline",
    sv: "Fungerar offline",
  },
  feat5_desc: {
    en: "No internet required",
    ru: "Интернет не требуется",
    es: "No requiere internet",
    fr: "Aucune connexion Internet requise",
    de: "Kein Internet erforderlich",
    it: "Nessuna connessione Internet richiesta",
    pt: "Não requer internet",
    zh: "无需联网",
    ja: "インターネット不要",
    ko: "인터넷 불필요",
    ar: "لا حاجة للإنترنت",
    hi: "इंटरनेट की आवश्यकता नहीं",
    tr: "İnternet gerekmez",
    pl: "Internet niewymagany",
    nl: "Geen internet vereist",
    uk: "Інтернет не потрібен",
    vi: "Không cần internet",
    th: "ไม่ต้องใช้อินเทอร์เน็ต",
    id: "Tidak perlu internet",
    sv: "Internet krävs inte",
  },

  theme_toggle_title: {
    en: "Toggle theme",
    ru: "Переключить тему",
    es: "Cambiar tema",
    fr: "Changer de thème",
    de: "Design wechseln",
    it: "Cambia tema",
    pt: "Alternar tema",
    zh: "切换主题",
    ja: "テーマを切り替え",
    ko: "테마 전환",
    ar: "تبديل السمة",
    hi: "थीम बदलें",
    tr: "Temayı değiştir",
    pl: "Przełącz motyw",
    nl: "Thema wisselen",
    uk: "Перемкнути тему",
    vi: "Chuyển đổi giao diện",
    th: "สลับธีม",
    id: "Ganti tema",
    sv: "Växla tema",
  },
  lang_toggle_title: {
    en: "Choose language",
    ru: "Выбрать язык",
    es: "Elegir idioma",
    fr: "Choisir la langue",
    de: "Sprache wählen",
    it: "Scegli lingua",
    pt: "Escolher idioma",
    zh: "选择语言",
    ja: "言語を選択",
    ko: "언어 선택",
    ar: "اختر اللغة",
    hi: "भाषा चुनें",
    tr: "Dil seç",
    pl: "Wybierz język",
    nl: "Kies taal",
    uk: "Обрати мову",
    vi: "Chọn ngôn ngữ",
    th: "เลือกภาษา",
    id: "Pilih bahasa",
    sv: "Välj språk",
  },
  lang_search_placeholder: {
    en: "Search language...",
    ru: "Поиск языка...",
    es: "Buscar idioma...",
    fr: "Rechercher une langue...",
    de: "Sprache suchen...",
    it: "Cerca lingua...",
    pt: "Pesquisar idioma...",
    zh: "搜索语言...",
    ja: "言語を検索...",
    ko: "언어 검색...",
    ar: "ابحث عن لغة...",
    hi: "भाषा खोजें...",
    tr: "Dil ara...",
    pl: "Szukaj języka...",
    nl: "Taal zoeken...",
    uk: "Пошук мови...",
    vi: "Tìm ngôn ngữ...",
    th: "ค้นหาภาษา...",
    id: "Cari bahasa...",
    sv: "Sök språk...",
  },
  eyedropper_title: {
    en: "Eyedropper",
    ru: "Пипетка",
    es: "Cuentagotas",
    fr: "Pipette",
    de: "Pipette",
    it: "Contagocce",
    pt: "Conta-gotas",
    zh: "取色器",
    ja: "スポイト",
    ko: "스포이드",
    ar: "القطارة",
    hi: "आईड्रॉपर",
    tr: "Damlalık",
    pl: "Pipeta",
    nl: "Pipet",
    uk: "Піпетка",
    vi: "Ống hút màu",
    th: "หลอดหยดสี",
    id: "Pipet",
    sv: "Pipett",
  },
  random_title: {
    en: "Random color",
    ru: "Случайный цвет",
    es: "Color aleatorio",
    fr: "Couleur aléatoire",
    de: "Zufällige Farbe",
    it: "Colore casuale",
    pt: "Cor aleatória",
    zh: "随机颜色",
    ja: "ランダムな色",
    ko: "임의 색상",
    ar: "لون عشوائي",
    hi: "यादृच्छिक रंग",
    tr: "Rastgele renk",
    pl: "Losowy kolor",
    nl: "Willekeurige kleur",
    uk: "Випадковий колір",
    vi: "Màu ngẫu nhiên",
    th: "สีสุ่ม",
    id: "Warna acak",
    sv: "Slumpmässig färg",
  },
  fav_title: {
    en: "Add to favorites",
    ru: "В избранное",
    es: "Añadir a favoritos",
    fr: "Ajouter aux favoris",
    de: "Zu Favoriten hinzufügen",
    it: "Aggiungi ai preferiti",
    pt: "Adicionar aos favoritos",
    zh: "添加到收藏",
    ja: "お気に入りに追加",
    ko: "즐겨찾기에 추가",
    ar: "أضف إلى المفضلة",
    hi: "पसंदीदा में जोड़ें",
    tr: "Favorilere ekle",
    pl: "Dodaj do ulubionych",
    nl: "Toevoegen aan favorieten",
    uk: "Додати в обране",
    vi: "Thêm vào yêu thích",
    th: "เพิ่มในรายการโปรด",
    id: "Tambahkan ke favorit",
    sv: "Lägg till som favorit",
  },
  copy_hex_title: {
    en: "Copy HEX",
    ru: "Копировать HEX",
    es: "Copiar HEX",
    fr: "Copier HEX",
    de: "HEX kopieren",
    it: "Copia HEX",
    pt: "Copiar HEX",
    zh: "复制 HEX",
    ja: "HEXをコピー",
    ko: "HEX 복사",
    ar: "نسخ HEX",
    hi: "HEX कॉपी करें",
    tr: "HEX'i kopyala",
    pl: "Kopiuj HEX",
    nl: "HEX kopiëren",
    uk: "Копіювати HEX",
    vi: "Sao chép HEX",
    th: "คัดลอก HEX",
    id: "Salin HEX",
    sv: "Kopiera HEX",
  },
  filter_title: {
    en: "Filter",
    ru: "Фильтр",
    es: "Filtro",
    fr: "Filtre",
    de: "Filter",
    it: "Filtro",
    pt: "Filtro",
    zh: "筛选",
    ja: "フィルター",
    ko: "필터",
    ar: "تصفية",
    hi: "फ़िल्टर",
    tr: "Filtre",
    pl: "Filtr",
    nl: "Filter",
    uk: "Фільтр",
    vi: "Bộ lọc",
    th: "ตัวกรอง",
    id: "Filter",
    sv: "Filter",
  },

  toast_saved_color: {
    en: "Color added to saved",
    ru: "Цвет добавлен в сохранённые",
    es: "Color añadido a guardados",
    fr: "Couleur ajoutée aux enregistrés",
    de: "Farbe zu Gespeichert hinzugefügt",
    it: "Colore aggiunto ai salvati",
    pt: "Cor adicionada aos salvos",
    zh: "颜色已添加到收藏",
    ja: "色を保存に追加しました",
    ko: "색상이 저장됨에 추가되었습니다",
    ar: "تمت إضافة اللون إلى المحفوظات",
    hi: "रंग सहेजे गए में जोड़ा गया",
    tr: "Renk kaydedilenlere eklendi",
    pl: "Kolor dodany do zapisanych",
    nl: "Kleur toegevoegd aan opgeslagen",
    uk: "Колір додано до збережених",
    vi: "Đã thêm màu vào mục đã lưu",
    th: "เพิ่มสีในรายการที่บันทึกแล้ว",
    id: "Warna ditambahkan ke tersimpan",
    sv: "Färg tillagd i sparade",
  },
  toast_copied_prefix: {
    en: "Copied: ",
    ru: "Скопировано: ",
    es: "Copiado: ",
    fr: "Copié : ",
    de: "Kopiert: ",
    it: "Copiato: ",
    pt: "Copiado: ",
    zh: "已复制: ",
    ja: "コピーしました: ",
    ko: "복사됨: ",
    ar: "تم النسخ: ",
    hi: "कॉपी किया गया: ",
    tr: "Kopyalandı: ",
    pl: "Skopiowano: ",
    nl: "Gekopieerd: ",
    uk: "Скопійовано: ",
    vi: "Đã sao chép: ",
    th: "คัดลอกแล้ว: ",
    id: "Disalin: ",
    sv: "Kopierat: ",
  },
  toast_no_eyedropper: {
    en: "Eyedropper not supported by browser",
    ru: "Пипетка не поддерживается браузером",
    es: "El navegador no admite el cuentagotas",
    fr: "La pipette n'est pas prise en charge par le navigateur",
    de: "Pipette wird vom Browser nicht unterstützt",
    it: "Il contagocce non è supportato dal browser",
    pt: "Conta-gotas não suportado pelo navegador",
    zh: "浏览器不支持取色器",
    ja: "このブラウザはスポイトに対応していません",
    ko: "브라우저에서 스포이드를 지원하지 않습니다",
    ar: "المتصفح لا يدعم القطارة",
    hi: "ब्राउज़र आईड्रॉपर का समर्थन नहीं करता",
    tr: "Tarayıcı damlalığı desteklemiyor",
    pl: "Przeglądarka nie obsługuje pipety",
    nl: "Pipet wordt niet ondersteund door browser",
    uk: "Браузер не підтримує піпетку",
    vi: "Trình duyệt không hỗ trợ ống hút màu",
    th: "เบราว์เซอร์ไม่รองรับหลอดหยดสี",
    id: "Browser tidak mendukung pipet",
    sv: "Pipetten stöds inte av webbläsaren",
  },
  toast_palette_exported: {
    en: "Palette exported",
    ru: "Палитра экспортирована",
    es: "Paleta exportada",
    fr: "Palette exportée",
    de: "Palette exportiert",
    it: "Tavolozza esportata",
    pt: "Paleta exportada",
    zh: "调色板已导出",
    ja: "パレットをエクスポートしました",
    ko: "팔레트가 내보내졌습니다",
    ar: "تم تصدير اللوحة",
    hi: "पैलेट निर्यात किया गया",
    tr: "Palet dışa aktarıldı",
    pl: "Paleta wyeksportowana",
    nl: "Palet geëxporteerd",
    uk: "Палітру експортовано",
    vi: "Đã xuất bảng màu",
    th: "ส่งออกจานสีแล้ว",
    id: "Palet diekspor",
    sv: "Palett exporterad",
  },
  toast_color_extracted: {
    en: "Color extracted from image",
    ru: "Цвет извлечён из изображения",
    es: "Color extraído de la imagen",
    fr: "Couleur extraite de l'image",
    de: "Farbe aus dem Bild extrahiert",
    it: "Colore estratto dall'immagine",
    pt: "Cor extraída da imagem",
    zh: "已从图片中提取颜色",
    ja: "画像から色を抽出しました",
    ko: "이미지에서 색상을 추출했습니다",
    ar: "تم استخراج اللون من الصورة",
    hi: "छवि से रंग निकाला गया",
    tr: "Görselden renk çıkarıldı",
    pl: "Wyodrębniono kolor z obrazu",
    nl: "Kleur uit afbeelding gehaald",
    uk: "Колір витягнуто із зображення",
    vi: "Đã trích xuất màu từ ảnh",
    th: "แยกสีจากรูปภาพแล้ว",
    id: "Warna diambil dari gambar",
    sv: "Färg extraherad från bild",
  },
  toast_theme_toggled: {
    en: "Theme switched",
    ru: "Тема переключена",
    es: "Tema cambiado",
    fr: "Thème changé",
    de: "Design gewechselt",
    it: "Tema cambiato",
    pt: "Tema alterado",
    zh: "主题已切换",
    ja: "テーマを切り替えました",
    ko: "테마가 전환되었습니다",
    ar: "تم تبديل السمة",
    hi: "थीम बदली गई",
    tr: "Tema değiştirildi",
    pl: "Motyw przełączony",
    nl: "Thema gewisseld",
    uk: "Тему змінено",
    vi: "Đã chuyển giao diện",
    th: "สลับธีมแล้ว",
    id: "Tema diganti",
    sv: "Tema växlat",
  },

  contrast_excellent: {
    en: "Excellent Contrast",
    ru: "Отличный контраст",
    es: "Contraste excelente",
    fr: "Excellent contraste",
    de: "Ausgezeichneter Kontrast",
    it: "Contrasto eccellente",
    pt: "Contraste excelente",
    zh: "极佳对比度",
    ja: "優れたコントラスト",
    ko: "우수한 대비",
    ar: "تباين ممتاز",
    hi: "उत्कृष्ट कंट्रास्ट",
    tr: "Mükemmel Kontrast",
    pl: "Doskonały kontrast",
    nl: "Uitstekend contrast",
    uk: "Відмінний контраст",
    vi: "Độ tương phản xuất sắc",
    th: "คอนทราสต์ยอดเยี่ยม",
    id: "Kontras Sangat Baik",
    sv: "Utmärkt kontrast",
  },
  contrast_good: {
    en: "Good Contrast",
    ru: "Хороший контраст",
    es: "Buen contraste",
    fr: "Bon contraste",
    de: "Guter Kontrast",
    it: "Buon contrasto",
    pt: "Bom contraste",
    zh: "良好对比度",
    ja: "良好なコントラスト",
    ko: "좋은 대비",
    ar: "تباين جيد",
    hi: "अच्छा कंट्रास्ट",
    tr: "İyi Kontrast",
    pl: "Dobry kontrast",
    nl: "Goed contrast",
    uk: "Гарний контраст",
    vi: "Độ tương phản tốt",
    th: "คอนทราสต์ดี",
    id: "Kontras Baik",
    sv: "Bra kontrast",
  },
  contrast_low: {
    en: "Low Contrast",
    ru: "Низкий контраст",
    es: "Contraste bajo",
    fr: "Faible contraste",
    de: "Geringer Kontrast",
    it: "Contrasto basso",
    pt: "Contraste baixo",
    zh: "对比度低",
    ja: "低コントラスト",
    ko: "낮은 대비",
    ar: "تباين منخفض",
    hi: "कम कंट्रास्ट",
    tr: "Düşük Kontrast",
    pl: "Niski kontrast",
    nl: "Laag contrast",
    uk: "Низький контраст",
    vi: "Độ tương phản thấp",
    th: "คอนทราสต์ต่ำ",
    id: "Kontras Rendah",
    sv: "Låg kontrast",
  },

  /* ---------- Страница Palette ---------- */
  palette_subtitle: {
    en: "Create, explore and manage beautiful color palettes",
    ru: "Создавайте, изучайте и управляйте красивыми палитрами",
  },
  palette_search_placeholder: {
    en: "Search palettes...",
    ru: "Поиск палитр...",
  },
  palette_filter_all: { en: "All Palettes", ru: "Все палитры" },
  palette_filter_fav: { en: "Favorites", ru: "Избранное" },
  palette_new: { en: "New Palette", ru: "Новая палитра" },
  palette_my_title: { en: "My Palettes", ru: "Мои палитры" },
  palette_count_word: { en: "palettes", ru: "палитр" },
  palette_colors_word: { en: "colors", ru: "цветов" },
  palette_created: { en: "Created", ru: "Создана" },
  palette_days_ago: { en: "days ago", ru: "дн. назад" },
  palette_delete: { en: "Delete", ru: "Удалить" },
  palette_tab_colors: { en: "Colors", ru: "Цвета" },
  palette_tab_info: { en: "Info", ru: "Инфо" },
  palette_add_color: { en: "Add Color", ru: "Добавить цвет" },
  palette_drop_hint: {
    en: "or drag & drop colors here",
    ru: "или перетащите цвета сюда",
  },
  palette_shades_title: { en: "Shades & Tints", ru: "Оттенки и тона" },
  palette_none_found: { en: "No palettes found", ru: "Палитры не найдены" },
  palette_edit_prompt: { en: "New HEX value:", ru: "Новое значение HEX:" },
  palette_rename_prompt: { en: "Palette name:", ru: "Название палитры:" },
  palette_cannot_delete_last: {
    en: "Keep at least one palette",
    ru: "Оставьте хотя бы одну палитру",
  },
  palette_delete_confirm: {
    en: "Delete this palette?",
    ru: "Удалить эту палитру?",
  },
  palette_new_prompt: {
    en: "New palette name:",
    ru: "Название новой палитры:",
  },
  palette_info_hint: {
    en: "This palette is great for UI, branding or illustration work.",
    ru: "Эта палитра отлично подходит для интерфейсов, брендинга и иллюстраций.",
  },
  toast_palette_created: { en: "Palette created", ru: "Палитра создана" },
  toast_color_added: { en: "Color added", ru: "Цвет добавлен" },
  toast_palette_link_copied: {
    en: "Palette colors copied to share",
    ru: "Цвета палитры скопированы для отправки",
  },

  /* ---------- Converter page ---------- */
  converter_subtitle: {
    en: "Convert colors between different formats",
    ru: "Конвертируйте цвета между разными форматами",
  },
  swap_colors: { en: "Swap Colors", ru: "Поменять цвета" },
  conv_card1_title: { en: "1. Choose Color", ru: "1. Выберите цвет" },
  conv_card1_sub: {
    en: "Pick a color to convert",
    ru: "Выберите цвет для конвертации",
  },
  conv_card2_title: { en: "2. Convert to", ru: "2. Конвертировать в" },
  conv_card2_sub: {
    en: "Choose formats to convert your color",
    ru: "Выберите форматы для конвертации цвета",
  },
  conv_card3_title: { en: "3. Preview", ru: "3. Превью" },
  conv_card3_sub: {
    en: "See how your color looks",
    ru: "Посмотрите, как выглядит ваш цвет",
  },
  conv_tip_title: { en: "Did you know?", ru: "Знаете ли вы?" },
  conv_tip_body: {
    en: "Different color models are useful for different purposes, RGB is for screens, CMYK for print, LAB for perceptual adjustments.",
    ru: "Разные цветовые модели полезны для разных задач: RGB — для экранов, CMYK — для печати, LAB — для восприятия и коррекции цвета.",
  },
  conv_color_name: { en: "Color Name", ru: "Название цвета" },
  conv_brightness: { en: "Brightness", ru: "Яркость" },
  conv_contrast_white: { en: "Contrast Ratio (White)", ru: "Контраст (белый)" },
  conv_contrast_black: {
    en: "Contrast Ratio (Black)",
    ru: "Контраст (чёрный)",
  },
  conv_harmonies_title: { en: "Color Harmonies", ru: "Цветовые гармонии" },
  conv_view_all: { en: "View All", ru: "Смотреть все" },
  harmony_complementary: { en: "Complementary", ru: "Комплементарная" },
  harmony_analogous: { en: "Analogous", ru: "Аналоговая" },
  harmony_triadic: { en: "Triadic", ru: "Триадная" },
  harmony_tetradic: { en: "Tetradic", ru: "Тетрадная" },
  harmony_monochromatic: { en: "Monochromatic", ru: "Монохромная" },
  toast_exported_json: { en: "JSON downloaded", ru: "JSON скачан" },
  toast_exported_css: {
    en: "CSS variable copied",
    ru: "CSS переменная скопирована",
  },
  toast_color_read: {
    en: "Color read from image",
    ru: "Цвет считан с изображения",
  },
  /* ---------- Страница Accessibility ---------- */
  a11y_subtitle: {
    en: "Check color contrast and accessibility compliance",
    ru: "Проверьте контраст цветов и соответствие требованиям доступности",
    fr: "Vérifiez le contraste des couleurs et la conformité en accessibilité",
    ar: "تحقّق من تباين الألوان ومطابقته لمعايير الوصول",
  },
  a11y_how_it_works: {
    en: "How it works",
    ru: "Как это работает",
    fr: "Comment ça marche",
    ar: "كيف يعمل",
  },
  a11y_wcag_guidelines: {
    en: "WCAG Guidelines",
    ru: "Рекомендации WCAG",
    fr: "Recommandations WCAG",
    ar: "إرشادات WCAG",
  },
  a11y_close: {
    en: "Close",
    ru: "Закрыть",
    fr: "Fermer",
    ar: "إغلاق",
  },
  a11y_how_p1: {
    en: "Contrast ratio compares the relative luminance of two colors. It ranges from 1:1 (identical) to 21:1 (black on white).",
    ru: "Коэффициент контраста сравнивает относительную яркость двух цветов: от 1:1 (одинаковые) до 21:1 (чёрный на белом).",
    fr: "Le rapport de contraste compare la luminance relative de deux couleurs. Il va de 1:1 (couleurs identiques) à 21:1 (noir sur blanc).",
    ar: "نسبة التباين تقارن السطوع النسبي للونين، وتتراوح من 1:1 (لونان متطابقان) إلى 21:1 (أسود على أبيض).",
  },
  a11y_how_p2: {
    en: "WCAG 2.1 asks for at least 4.5:1 for normal text and 3:1 for large text at level AA. Level AAA raises these to 7:1 and 4.5:1.",
    ru: "WCAG 2.1 требует минимум 4.5:1 для обычного текста и 3:1 для крупного на уровне AA. Уровень AAA поднимает планку до 7:1 и 4.5:1.",
    fr: "WCAG 2.1 exige au moins 4,5:1 pour le texte normal et 3:1 pour le grand texte au niveau AA. Le niveau AAA porte ces seuils à 7:1 et 4,5:1.",
    ar: "تشترط WCAG 2.1 نسبة 4.5:1 على الأقل للنص العادي و3:1 للنص الكبير عند المستوى AA، ويرفعها المستوى AAA إلى 7:1 و4.5:1.",
  },
  a11y_how_p3: {
    en: "Large text means 18pt and above, or 14pt bold and above. Icons and interface controls follow the 3:1 threshold.",
    ru: "Крупный текст — от 18pt или от 14pt полужирного. Для иконок и элементов управления действует порог 3:1.",
    fr: "Le grand texte commence à 18 pt, ou 14 pt en gras. Les icônes et les contrôles d'interface suivent le seuil de 3:1.",
    ar: "النص الكبير يبدأ من 18pt أو من 14pt غامق. أما الأيقونات وعناصر التحكم فيسري عليها حدّ 3:1.",
  },
  a11y_select_title: {
    en: "Select Colors",
    ru: "Выбор цветов",
    fr: "Choix des couleurs",
    ar: "اختيار الألوان",
  },
  a11y_select_sub: {
    en: "Choose text and background colors to test",
    ru: "Укажите цвет текста и фона для проверки",
    fr: "Indiquez la couleur du texte et du fond à tester",
    ar: "حدّد لون النص والخلفية للفحص",
  },
  a11y_text_color: {
    en: "Text Color",
    ru: "Цвет текста",
    fr: "Couleur du texte",
    ar: "لون النص",
  },
  a11y_bg_color: {
    en: "Background Color",
    ru: "Цвет фона",
    fr: "Couleur de fond",
    ar: "لون الخلفية",
  },
  a11y_quick_presets: {
    en: "Quick Presets",
    ru: "Быстрые пресеты",
    fr: "Préréglages rapides",
    ar: "إعدادات سريعة",
  },
  a11y_add_preset: {
    en: "Save current pair as a preset",
    ru: "Сохранить текущую пару как пресет",
    fr: "Enregistrer la paire actuelle",
    ar: "حفظ الزوج الحالي",
  },
  a11y_preset_added: {
    en: "Preset saved",
    ru: "Пресет сохранён",
    fr: "Préréglage enregistré",
    ar: "تم حفظ الإعداد",
  },
  a11y_preset_exists: {
    en: "This pair is already saved",
    ru: "Такая пара уже сохранена",
    fr: "Cette paire est déjà enregistrée",
    ar: "هذا الزوج محفوظ مسبقًا",
  },
  a11y_preset_removed: {
    en: "Preset removed",
    ru: "Пресет удалён",
    fr: "Préréglage supprimé",
    ar: "تم حذف الإعداد",
  },
  a11y_results_title: {
    en: "Results",
    ru: "Результаты",
    fr: "Résultats",
    ar: "النتائج",
  },
  a11y_results_sub: {
    en: "Contrast ratio and compliance status",
    ru: "Коэффициент контраста и соответствие стандарту",
    fr: "Rapport de contraste et conformité",
    ar: "نسبة التباين ومدى المطابقة",
  },
  a11y_status_excellent: {
    en: "Excellent Contrast",
    ru: "Отличный контраст",
    fr: "Excellent contraste",
    ar: "تباين ممتاز",
  },
  a11y_status_good: {
    en: "Good Contrast",
    ru: "Хороший контраст",
    fr: "Bon contraste",
    ar: "تباين جيد",
  },
  a11y_status_limited: {
    en: "Large Text Only",
    ru: "Только для крупного текста",
    fr: "Grand texte uniquement",
    ar: "للنص الكبير فقط",
  },
  a11y_status_poor: {
    en: "Low Contrast",
    ru: "Низкий контраст",
    fr: "Contraste faible",
    ar: "تباين ضعيف",
  },
  a11y_group_aa: {
    en: "WCAG 2.1 AA",
    ru: "WCAG 2.1 AA",
    fr: "WCAG 2.1 AA",
    ar: "WCAG 2.1 AA",
  },
  a11y_group_aaa: {
    en: "WCAG 2.1 AAA",
    ru: "WCAG 2.1 AAA",
    fr: "WCAG 2.1 AAA",
    ar: "WCAG 2.1 AAA",
  },
  a11y_normal_text: {
    en: "Normal Text",
    ru: "Обычный текст",
    fr: "Texte normal",
    ar: "نص عادي",
  },
  a11y_large_text: {
    en: "Large Text",
    ru: "Крупный текст",
    fr: "Grand texte",
    ar: "نص كبير",
  },
  a11y_pass: {
    en: "Pass",
    ru: "Пройдено",
    fr: "Conforme",
    ar: "مطابق",
  },
  a11y_fail: {
    en: "Fail",
    ru: "Не пройдено",
    fr: "Non conforme",
    ar: "غير مطابق",
  },
  a11y_meaning_title: {
    en: "What this means",
    ru: "Что это значит",
    fr: "Ce que cela signifie",
    ar: "ماذا يعني ذلك",
  },
  a11y_meaning_aaa: {
    en: "This color combination meets all WCAG 2.1 AA and AAA standards for text readability.",
    ru: "Эта комбинация соответствует всем требованиям WCAG 2.1 уровней AA и AAA к читаемости текста.",
    fr: "Cette combinaison respecte les niveaux AA et AAA de WCAG 2.1 pour la lisibilité du texte.",
    ar: "هذه التركيبة تستوفي مستويي AA وAAA في WCAG 2.1 لوضوح النص.",
  },
  a11y_meaning_aa: {
    en: "This combination meets WCAG 2.1 AA for all text sizes and AAA for large text only.",
    ru: "Комбинация соответствует уровню AA для любого размера текста и AAA — только для крупного текста.",
    fr: "Cette combinaison respecte le niveau AA pour toutes les tailles de texte, et AAA uniquement pour le grand texte.",
    ar: "تستوفي التركيبة المستوى AA لكل أحجام النص، والمستوى AAA للنص الكبير فقط.",
  },
  a11y_meaning_large_only: {
    en: "This combination is only safe for large text (18pt+, or 14pt bold). Increase the difference in lightness for body text.",
    ru: "Комбинация подходит только для крупного текста (от 18pt или 14pt полужирный). Для основного текста увеличьте разницу в светлоте.",
    fr: "Cette combinaison ne convient qu'au grand texte (18 pt et plus, ou 14 pt en gras). Augmentez l'écart de luminosité pour le texte courant.",
    ar: "تصلح هذه التركيبة للنص الكبير فقط (من 18pt أو 14pt غامق). زد الفارق في الإضاءة لاستخدامها في النص العادي.",
  },
  a11y_meaning_fail: {
    en: "This combination fails WCAG 2.1 at every level. Pick a lighter or darker text color before using it.",
    ru: "Комбинация не проходит WCAG 2.1 ни на одном уровне. Выберите более светлый или более тёмный цвет текста.",
    fr: "Cette combinaison échoue à tous les niveaux de WCAG 2.1. Choisissez un texte plus clair ou plus foncé avant de l'utiliser.",
    ar: "لا تجتاز هذه التركيبة أي مستوى في WCAG 2.1. اختر لون نص أفتح أو أغمق قبل استخدامها.",
  },
  a11y_view_report: {
    en: "View Full Report",
    ru: "Полный отчёт",
    fr: "Rapport complet",
    ar: "التقرير الكامل",
  },
  a11y_copy_report: {
    en: "Copy report",
    ru: "Скопировать отчёт",
    fr: "Copier le rapport",
    ar: "نسخ التقرير",
  },
  a11y_report_text: {
    en: "Text color",
    ru: "Цвет текста",
    fr: "Couleur du texte",
    ar: "لون النص",
  },
  a11y_report_bg: {
    en: "Background color",
    ru: "Цвет фона",
    fr: "Couleur de fond",
    ar: "لون الخلفية",
  },
  a11y_report_ratio: {
    en: "Contrast ratio",
    ru: "Коэффициент контраста",
    fr: "Rapport de contraste",
    ar: "نسبة التباين",
  },
  a11y_report_lum_text: {
    en: "Text luminance",
    ru: "Яркость текста",
    fr: "Luminance du texte",
    ar: "سطوع النص",
  },
  a11y_report_lum_bg: {
    en: "Background luminance",
    ru: "Яркость фона",
    fr: "Luminance du fond",
    ar: "سطوع الخلفية",
  },
  a11y_report_best: {
    en: "Highest level passed",
    ru: "Максимальный уровень",
    fr: "Niveau maximal atteint",
    ar: "أعلى مستوى مُحقَّق",
  },
  a11y_sim_title: {
    en: "Color Blindness Simulator",
    ru: "Симулятор дальтонизма",
    fr: "Simulateur de daltonisme",
    ar: "محاكي عمى الألوان",
  },
  a11y_sim_sub: {
    en: "See how colors appear to different types of color blindness",
    ru: "Посмотрите, как цвета выглядят при разных типах дальтонизма",
    fr: "Voyez vos couleurs selon les différents types de daltonisme",
    ar: "شاهد كيف تبدو الألوان لأنواع مختلفة من عمى الألوان",
  },
  a11y_vision_normal: {
    en: "Normal Vision",
    ru: "Обычное зрение",
    fr: "Vision normale",
    ar: "رؤية طبيعية",
  },
  a11y_vision_deuteranopia: {
    en: "Deuteranopia",
    ru: "Дейтеранопия",
    fr: "Deutéranopie",
    ar: "ديوترانوبيا (عمى الأخضر)",
  },
  a11y_vision_protanopia: {
    en: "Protanopia",
    ru: "Протанопия",
    fr: "Protanopie",
    ar: "بروتانوبيا (عمى الأحمر)",
  },
  a11y_vision_tritanopia: {
    en: "Tritanopia",
    ru: "Тританопия",
    fr: "Tritanopie",
    ar: "تريتانوبيا (عمى الأزرق)",
  },
  a11y_vision_monochromacy: {
    en: "Monochromacy",
    ru: "Монохромазия",
    fr: "Monochromatisme",
    ar: "رؤية أحادية اللون",
  },
  a11y_preview_title: {
    en: "Preview",
    ru: "Превью",
    fr: "Aperçu",
    ar: "معاينة",
  },
  a11y_preview_sub: {
    en: "See how your colors look together",
    ru: "Посмотрите, как цвета работают вместе",
    fr: "Voyez le rendu de vos couleurs ensemble",
    ar: "شاهد كيف يعمل اللونان معًا",
  },
  a11y_preview_heading: {
    en: "Large Heading",
    ru: "Крупный заголовок",
    fr: "Grand titre",
    ar: "عنوان كبير",
  },
  a11y_preview_body: {
    en: "This is a paragraph of text that demonstrates how your selected colors work together for readability.",
    ru: "Это абзац текста, который показывает, насколько выбранные цвета удобны для чтения.",
    fr: "Ceci est un paragraphe qui montre à quel point les couleurs choisies sont confortables à lire.",
    ar: "هذه فقرة نصية توضّح مدى سهولة قراءة الألوان التي اخترتها.",
  },
  a11y_preview_link: {
    en: "Link Example",
    ru: "Пример ссылки",
    fr: "Exemple de lien",
    ar: "مثال على رابط",
  },
  a11y_preview_caption: {
    en: "The quick brown fox jumps over the lazy dog.",
    ru: "Съешь ещё этих мягких французских булок да выпей чаю.",
    fr: "Portez ce vieux whisky au juge blond qui fume.",
    ar: "أبجد هوز حطي كلمن سعفص قرشت ثخذ ضظغ.",
  },
  a11y_preview_caption_sim: {
    en: "Preview shown as seen with",
    ru: "Превью показано так, как его видят при: ",
    fr: "Aperçu tel que perçu avec :",
    ar: "المعاينة كما تُرى مع:",
  },
  a11y_suggest_title: {
    en: "Color Suggestions",
    ru: "Подбор цветов",
    fr: "Couleurs suggérées",
    ar: "اقتراحات الألوان",
  },
  a11y_suggest_sub: {
    en: "Accessible alternatives for your color combination",
    ru: "Доступные альтернативы для вашей комбинации",
    fr: "Alternatives accessibles pour votre combinaison",
    ar: "بدائل متاحة لتركيبتك اللونية",
  },
  a11y_generate_more: {
    en: "Generate More",
    ru: "Ещё варианты",
    fr: "Autres variantes",
    ar: "خيارات أخرى",
  },
  a11y_apply_suggestion: {
    en: "Use as text color",
    ru: "Применить как цвет текста",
    fr: "Utiliser comme couleur de texte",
    ar: "استخدامه لونًا للنص",
  },
  a11y_suggestion_applied: {
    en: "Text color updated",
    ru: "Цвет текста обновлён",
    fr: "Couleur du texte mise à jour",
    ar: "تم تحديث لون النص",
  },
  a11y_no_suggestions: {
    en: "No accessible alternatives found for this background.",
    ru: "Для этого фона доступных альтернатив не нашлось.",
    fr: "Aucune alternative accessible pour ce fond.",
    ar: "لا توجد بدائل مناسبة لهذه الخلفية.",
  },
  toast_copy_failed: {
    en: "Copy failed",
    ru: "Не удалось скопировать",
    fr: "Échec de la copie",
    ar: "تعذّر النسخ",
  },

  /* ---------- Страница Resources ---------- */
  res_subtitle: {
    en: "Tools, guides and resources to master color and build beautiful experiences.",
    ru: "Инструменты, руководства и материалы, чтобы уверенно работать с цветом.",
    fr: "Outils, guides et ressources pour maîtriser la couleur et créer de belles interfaces.",
    ar: "أدوات وأدلة وموارد لإتقان التعامل مع الألوان وبناء واجهات جميلة.",
  },
  res_search_placeholder: {
    en: "Search resources...",
    ru: "Поиск по материалам...",
    fr: "Rechercher une ressource...",
    ar: "ابحث في الموارد...",
  },
  res_empty: {
    en: "Nothing matches your search.",
    ru: "По запросу ничего не найдено.",
    fr: "Aucun résultat pour cette recherche.",
    ar: "لا توجد نتائج مطابقة.",
  },
  res_more_soon: {
    en: "This section is still in the works",
    ru: "Этот раздел ещё в работе",
    fr: "Cette section est encore en préparation",
    ar: "هذا القسم قيد الإعداد",
  },
  res_badge_new: {
    en: "New",
    ru: "Новое",
    fr: "Nouveau",
    ar: "جديد",
  },
  res_guides_title: {
    en: "Guides & Articles",
    ru: "Руководства и статьи",
    fr: "Guides et articles",
    ar: "أدلة ومقالات",
  },
  res_guides_desc: {
    en: "In-depth guides and best practices for working with color.",
    ru: "Подробные руководства и практики работы с цветом.",
    fr: "Guides détaillés et bonnes pratiques pour travailler la couleur.",
    ar: "أدلة مفصّلة وأفضل الممارسات في التعامل مع اللون.",
  },
  res_view_all_guides: {
    en: "View all guides",
    ru: "Все руководства",
    fr: "Tous les guides",
    ar: "كل الأدلة",
  },
  res_guide_theory: {
    en: "Color Theory Basics",
    ru: "Основы теории цвета",
    fr: "Bases de la théorie des couleurs",
    ar: "أساسيات نظرية الألوان",
  },
  res_guide_theory_sub: {
    en: "Understand hue, saturation, and more",
    ru: "Оттенок, насыщенность и светлота",
    fr: "Teinte, saturation et luminosité",
    ar: "درجة اللون والتشبع والإضاءة",
  },
  res_guide_theory_body: {
    en: "Every color can be described by three properties: hue (its position on the color wheel), saturation (how vivid it is), and lightness (how much white or black it contains). Working in HSL instead of HEX makes it much easier to build a palette, because you can hold the hue steady and change only lightness to get a consistent set of shades.",
    ru: "Любой цвет описывается тремя свойствами: тон (положение на цветовом круге), насыщенность (яркость) и светлота (сколько в нём белого или чёрного). Работать в HSL удобнее, чем в HEX: удерживая тон и меняя только светлоту, вы получаете согласованный набор оттенков.",
    fr: "Toute couleur se décrit par trois propriétés : la teinte (sa position sur la roue), la saturation (son intensité) et la luminosité (la quantité de blanc ou de noir qu'elle contient). Travailler en HSL plutôt qu'en HEX facilite la construction d'une palette : en gardant la teinte fixe et en ne changeant que la luminosité, vous obtenez une série de nuances cohérentes.",
    ar: "يوصف أي لون بثلاث خصائص: درجة اللون (موضعه على عجلة الألوان)، والتشبع (قوته)، والإضاءة (مقدار الأبيض أو الأسود فيه). والعمل بنظام HSL أسهل من HEX عند بناء لوحة ألوان: تثبّت درجة اللون وتغيّر الإضاءة وحدها فتحصل على تدرّجات متناسقة.",
  },
  res_guide_a11y: {
    en: "How to Use Color Accessibility",
    ru: "Как проверять доступность цвета",
    fr: "Utiliser la couleur de façon accessible",
    ar: "كيف تتحقق من إتاحة الألوان",
  },
  res_guide_a11y_sub: {
    en: "Build inclusive and accessible designs",
    ru: "Инклюзивные и доступные интерфейсы",
    fr: "Concevoir des interfaces inclusives",
    ar: "تصميمات شاملة يسهل الوصول إليها",
  },
  res_guide_a11y_body: {
    en: "Color alone should never carry meaning: pair it with text, icons or patterns so the message survives for people who cannot distinguish certain hues. Check every text and background pair against WCAG on the Accessibility page, and remember that interface controls and icons need at least 3:1 against their surroundings.",
    ru: "Цвет не должен быть единственным носителем смысла: дублируйте его текстом, иконкой или паттерном. Проверяйте каждую пару «текст — фон» по WCAG на странице «Доступность» и помните, что элементы управления и иконки требуют минимум 3:1 к окружению.",
    fr: "La couleur ne doit jamais porter seule une information : associez-la à du texte, une icône ou un motif, afin que le message reste compréhensible pour qui ne distingue pas certaines teintes. Vérifiez chaque paire texte/fond selon WCAG sur la page Accessibilité, et rappelez-vous que les contrôles et les icônes exigent au moins 3:1 par rapport à leur environnement.",
    ar: "لا ينبغي أن يكون اللون وحده حاملًا للمعنى: اقرنه بنص أو أيقونة أو نمط ليبقى المعنى واضحًا لمن لا يميّز بعض الدرجات. افحص كل زوج «نص وخلفية» وفق WCAG في صفحة الوصول، وتذكّر أن عناصر التحكم والأيقونات تحتاج 3:1 على الأقل مقابل محيطها.",
  },
  res_guide_palettes: {
    en: "Choosing Better Color Palettes",
    ru: "Как собирать хорошие палитры",
    fr: "Composer de meilleures palettes",
    ar: "كيف تبني لوحات ألوان أفضل",
  },
  res_guide_palettes_sub: {
    en: "Tips for creating beautiful color schemes",
    ru: "Приёмы для гармоничных схем",
    fr: "Conseils pour des harmonies réussies",
    ar: "نصائح لتركيبات متناغمة",
  },
  res_guide_palettes_body: {
    en: "Start from one base color and derive the rest: a complementary hue for accents, two or three neutrals for surfaces, and a spread of lightness steps for states. Keep the number of saturated colors small — most of the interface should be neutral, with saturation reserved for the elements you actually want people to notice.",
    ru: "Начинайте с одного базового цвета: добавьте комплементарный для акцентов, два-три нейтральных для поверхностей и шкалу светлот для состояний. Насыщенных цветов должно быть мало — большая часть интерфейса нейтральна, а насыщенность оставляйте тому, что действительно должно привлекать внимание.",
    fr: "Partez d'une couleur de base et déduisez le reste : une teinte complémentaire pour les accents, deux ou trois neutres pour les surfaces, et une échelle de luminosité pour les états. Limitez le nombre de couleurs saturées — l'essentiel de l'interface doit rester neutre, la saturation étant réservée à ce que l'on veut vraiment faire remarquer.",
    ar: "ابدأ من لون أساسي واشتقّ الباقي: لون مكمّل للتمييز، ولونان أو ثلاثة محايدة للأسطح، وسلّم إضاءة للحالات المختلفة. أبقِ الألوان المشبعة قليلة؛ فمعظم الواجهة ينبغي أن يكون محايدًا، والتشبع يُترك لما تريد لفت الانتباه إليه فعلًا.",
  },
  res_guide_gradients: {
    en: "Working with Gradients",
    ru: "Работа с градиентами",
    fr: "Travailler les dégradés",
    ar: "العمل مع التدرجات",
  },
  res_guide_gradients_sub: {
    en: "Create smooth and dynamic gradients",
    ru: "Плавные и живые переходы",
    fr: "Des transitions douces et vivantes",
    ar: "انتقالات ناعمة وحيوية",
  },
  res_guide_gradients_body: {
    en: "Gradients between colors far apart on the wheel pass through muddy midpoints. Keep the hue distance short, or add an intermediate stop that stays saturated. Interpolating in a perceptual space such as OKLCH gives noticeably cleaner results than plain sRGB, especially for long transitions across a large surface.",
    ru: "Градиент между далёкими на круге цветами проходит через грязную середину. Держите расстояние по тону небольшим или добавьте промежуточную точку, сохраняющую насыщенность. Интерполяция в перцептивном пространстве вроде OKLCH даёт заметно чище результат, чем обычный sRGB.",
    fr: "Un dégradé entre deux couleurs éloignées sur la roue traverse un milieu terne. Gardez une faible distance de teinte ou ajoutez une étape intermédiaire qui reste saturée. Une interpolation dans un espace perceptuel comme OKLCH donne un résultat nettement plus propre que le sRGB, surtout sur de longues transitions.",
    ar: "التدرّج بين لونين متباعدين على العجلة يمرّ بمنتصف باهت. أبقِ المسافة اللونية قصيرة أو أضف نقطة وسطى محتفظة بتشبعها. والاشتقاق في فضاء إدراكي مثل OKLCH يعطي نتيجة أنظف بكثير من sRGB، خصوصًا في الانتقالات الطويلة.",
  },
  res_tools_title: {
    en: "Tools & Utilities",
    ru: "Инструменты",
    fr: "Outils et utilitaires",
    ar: "أدوات ومساعدات",
  },
  res_tools_desc: {
    en: "Helpful tools to generate, analyze and convert colors.",
    ru: "Помогают создавать, анализировать и конвертировать цвета.",
    fr: "Des outils pour générer, analyser et convertir les couleurs.",
    ar: "أدوات لتوليد الألوان وتحليلها وتحويلها.",
  },
  res_view_all_tools: {
    en: "View all tools",
    ru: "Все инструменты",
    fr: "Tous les outils",
    ar: "كل الأدوات",
  },
  res_tool_contrast: {
    en: "Contrast Checker",
    ru: "Проверка контраста",
    fr: "Vérificateur de contraste",
    ar: "فاحص التباين",
  },
  res_tool_contrast_sub: {
    en: "Check contrast between two colors",
    ru: "Контраст между двумя цветами",
    fr: "Contrôler le contraste entre deux couleurs",
    ar: "قياس التباين بين لونين",
  },
  res_tool_gradient: {
    en: "Gradient Generator",
    ru: "Генератор градиентов",
    fr: "Générateur de dégradés",
    ar: "مولّد التدرجات",
  },
  res_tool_gradient_sub: {
    en: "Create and customize gradients",
    ru: "Создание и настройка градиентов",
    fr: "Créer et régler des dégradés",
    ar: "إنشاء التدرجات وضبطها",
  },
  res_tool_cvd: {
    en: "Color Blindness Simulator",
    ru: "Симулятор дальтонизма",
    fr: "Simulateur de daltonisme",
    ar: "محاكي عمى الألوان",
  },
  res_tool_cvd_sub: {
    en: "Simulate how colors appear to others",
    ru: "Как цвета видят другие люди",
    fr: "Voir les couleurs comme les autres",
    ar: "كيف يرى الآخرون ألوانك",
  },
  res_tool_extractor: {
    en: "Image Color Extractor",
    ru: "Цвета с картинки",
    fr: "Extracteur de couleurs",
    ar: "استخراج ألوان الصورة",
  },
  res_tool_extractor_sub: {
    en: "Extract colors from any image",
    ru: "Извлечение цветов из изображения",
    fr: "Extraire les couleurs d'une image",
    ar: "استخراج الألوان من أي صورة",
  },
  res_assets_title: {
    en: "Downloads & Assets",
    ru: "Файлы и ресурсы",
    fr: "Téléchargements et ressources",
    ar: "ملفات وموارد",
  },
  res_assets_desc: {
    en: "Free resources, templates and color assets for your projects.",
    ru: "Бесплатные шаблоны и материалы для ваших проектов.",
    fr: "Ressources, modèles et fichiers couleur gratuits pour vos projets.",
    ar: "موارد وقوالب وملفات ألوان مجانية لمشاريعك.",
  },
  res_view_all_assets: {
    en: "View all assets",
    ru: "Все материалы",
    fr: "Toutes les ressources",
    ar: "كل الموارد",
  },
  res_asset_templates: {
    en: "Color Palette Templates",
    ru: "Шаблоны палитр",
    fr: "Modèles de palettes",
    ar: "قوالب لوحات الألوان",
  },
  res_asset_templates_sub: {
    en: "Ready-to-use palette templates",
    ru: "Готовые палитры для работы",
    fr: "Palettes prêtes à l'emploi",
    ar: "لوحات جاهزة للاستخدام",
  },
  res_asset_uikits: {
    en: "UI Kits & Components",
    ru: "UI-киты и компоненты",
    fr: "Kits UI et composants",
    ar: "أطقم واجهات ومكوّنات",
  },
  res_asset_uikits_sub: {
    en: "Figma and HTML color components",
    ru: "Цветовые компоненты для Figma и HTML",
    fr: "Composants couleur Figma et HTML",
    ar: "مكوّنات ألوان لـ Figma وHTML",
  },
  res_asset_uikits_body: {
    en: "A UI kit is only as good as its color tokens. Define surfaces, borders, text levels and accents once, name them by role rather than by hue, and every component built on top stays consistent — and switching to a light or high-contrast theme becomes a matter of swapping values, not rewriting components.",
    ru: "UI-кит держится на цветовых токенах. Опишите поверхности, границы, уровни текста и акценты один раз и называйте их по роли, а не по оттенку — тогда все компоненты останутся согласованными, а переключение на светлую иливысококонтрастную тему сведётся к подмене значений.",
    fr: "Un kit UI ne vaut que par ses jetons de couleur. Définissez une fois les surfaces, les bordures, les niveaux de texte et les accents, nommez-les par leur rôle et non par leur teinte : tous les composants restent cohérents, et passer à un thème clair ou très contrasté revient à changer des valeurs, pas à réécrire les composants.",
    ar: "قيمة طقم الواجهة في رموز ألوانه. عرّف الأسطح والحدود ومستويات النص وألوان التمييز مرة واحدة، وسمِّها بحسب وظيفتها لا بحسب درجتها؛ عندئذ تبقى المكوّنات متسقة، ويصبح التحويل إلى سمة فاتحة أو عالية التباين مجرد تبديل قيم لا إعادة كتابة.",
  },
  res_asset_gradients: {
    en: "Gradient Backgrounds",
    ru: "Градиентные фоны",
    fr: "Fonds en dégradé",
    ar: "خلفيات متدرجة",
  },
  res_asset_gradients_sub: {
    en: "Beautiful gradient backgrounds",
    ru: "Красивые фоновые градиенты",
    fr: "De beaux arrière-plans dégradés",
    ar: "خلفيات تدرّج جميلة",
  },
  res_asset_swatches: {
    en: "Color Icons & Swatches",
    ru: "Наборы образцов цвета",
    fr: "Nuanciers et icônes",
    ar: "مجموعات عيّنات الألوان",
  },
  res_asset_swatches_sub: {
    en: "Download palettes as JSON",
    ru: "Скачать палитры в формате JSON",
    fr: "Télécharger les palettes en JSON",
    ar: "تنزيل اللوحات بصيغة JSON",
  },
  res_systems_title: {
    en: "Color Systems",
    ru: "Цветовые системы",
    fr: "Systèmes de couleur",
    ar: "أنظمة الألوان",
  },
  res_systems_desc: {
    en: "Explore popular color systems and standards.",
    ru: "Популярные цветовые системы и стандарты.",
    fr: "Découvrez les systèmes et standards les plus utilisés.",
    ar: "أشهر أنظمة الألوان والمعايير.",
  },
  res_explore_systems: {
    en: "Explore all systems",
    ru: "Все системы",
    fr: "Tous les systèmes",
    ar: "كل الأنظمة",
  },
  res_inspiration_title: {
    en: "Color Inspiration",
    ru: "Вдохновение",
    fr: "Inspiration",
    ar: "إلهام لوني",
  },
  res_inspiration_desc: {
    en: "Discover beautiful color palettes and trends.",
    ru: "Готовые палитры и актуальные сочетания.",
    fr: "Des palettes et des tendances à explorer.",
    ar: "لوحات جاهزة وتركيبات رائجة.",
  },
  res_browse_palettes: {
    en: "Browse palettes",
    ru: "Смотреть палитры",
    fr: "Parcourir les palettes",
    ar: "تصفّح اللوحات",
  },
  res_help_title: {
    en: "Help & Support",
    ru: "Помощь и поддержка",
    fr: "Aide et support",
    ar: "المساعدة والدعم",
  },
  res_help_desc: {
    en: "Get help, report issues or request features.",
    ru: "Справка, сообщения об ошибках и предложения.",
    fr: "Obtenir de l'aide, signaler un problème ou proposer une idée.",
    ar: "احصل على المساعدة أو أبلغ عن مشكلة أو اقترح فكرة.",
  },
  res_help_docs: {
    en: "Documentation",
    ru: "Документация",
    fr: "Documentation",
    ar: "التوثيق",
  },
  res_help_docs_sub: {
    en: "Complete usage guide",
    ru: "Полное руководство",
    fr: "Guide d'utilisation complet",
    ar: "دليل الاستخدام الكامل",
  },
  res_help_docs_body: {
    en: "Every page of the app works offline and stores your palettes, saved colors and presets in the browser. Clearing site data resets them, so export anything you want to keep as JSON from the Export menu before wiping your browser storage.",
    ru: "Все страницы приложения работают офлайн и хранят палитры, сохранённые цвета и пресеты в браузере. Очистка данных сайта их сбрасывает, поэтому важное выгружайте в JSON через меню «Экспорт».",
    fr: "Toutes les pages fonctionnent hors ligne et conservent vos palettes, vos couleurs enregistrées et vos préréglages dans le navigateur. Effacer les données du site les supprime : exportez en JSON ce que vous voulez garder via le menu Exporter.",
    ar: "تعمل جميع الصفحات دون اتصال وتحفظ لوحاتك وألوانك المحفوظة وإعداداتك داخل المتصفح. ومسح بيانات الموقع يحذفها، لذا صدّر ما يهمّك بصيغة JSON من قائمة «تصدير».",
  },
  res_help_faq: {
    en: "FAQ",
    ru: "Частые вопросы",
    fr: "Questions fréquentes",
    ar: "الأسئلة الشائعة",
  },
  res_help_faq_sub: {
    en: "Frequently asked questions",
    ru: "Ответы на частые вопросы",
    fr: "Réponses aux questions courantes",
    ar: "إجابات عن أكثر الأسئلة تكرارًا",
  },
  res_help_faq_body: {
    en: "Why does the eyedropper only work in some browsers? It relies on the EyeDropper API, which Chrome and Edge support but Firefox and Safari do not. Why does a contrast ratio differ from another tool? Some checkers round differently or measure against a different background — the formula here follows WCAG 2.1 exactly.",
    ru: "Почему пипетка работает не везде? Она использует EyeDropper API, который поддерживают Chrome и Edge, но не Firefox и Safari. Почему контраст отличается от другого сервиса? Часть инструментов иначе округляет или берёт другой фон — здесь формула точно соответствует WCAG 2.1.",
    fr: "Pourquoi la pipette ne fonctionne-t-elle pas partout ? Elle repose sur l'API EyeDropper, prise en charge par Chrome et Edge mais pas par Firefox ni Safari. Pourquoi le rapport de contraste diffère-t-il d'un autre outil ? Certains arrondissent autrement ou mesurent sur un autre fond ; ici la formule suit exactement WCAG 2.1.",
    ar: "لماذا لا تعمل القطّارة في كل المتصفحات؟ لأنها تعتمد على واجهة EyeDropper التي يدعمها Chrome وEdge دون Firefox وSafari. ولماذا تختلف نسبة التباين عن أداة أخرى؟ لأن بعض الأدوات تقرّب الأرقام أو تقيس على خلفية مختلفة، بينما المعادلة هنا تتبع WCAG 2.1 بدقّة.",
  },
  res_help_issue: {
    en: "Report an Issue",
    ru: "Сообщить об ошибке",
    fr: "Signaler un problème",
    ar: "الإبلاغ عن مشكلة",
  },
  res_help_issue_sub: {
    en: "Help us improve",
    ru: "Помогите стать лучше",
    fr: "Aidez-nous à progresser",
    ar: "ساعدنا في التحسين",
  },
  res_help_issue_body: {
    en: "A useful bug report needs three things: what you did, what you expected, and what happened instead. Add your browser and version, and a HEX value if the problem involves a specific color — that is usually enough to reproduce the issue on the first try.",
    ru: "Полезный отчёт содержит три вещи: что вы сделали, что ожидали и что произошло. Добавьте браузер с версией и HEX-значение, если проблема связана с конкретным цветом — обычно этого достаточно, чтобы воспроизвести ошибку с первого раза.",
    fr: "Un bon rapport de bug contient trois éléments : ce que vous avez fait, ce que vous attendiez et ce qui s'est produit. Ajoutez votre navigateur et sa version, ainsi que la valeur HEX si le problème concerne une couleur précise — cela suffit généralement à reproduire le cas du premier coup.",
    ar: "البلاغ المفيد يتضمّن ثلاثة أمور: ما الذي فعلته، وما الذي توقّعته، وما الذي حدث فعلًا. أضف اسم المتصفح وإصداره، وقيمة HEX إن كانت المشكلة مرتبطة بلون بعينه؛ يكفي هذا عادةً لإعادة إنتاج المشكلة من أول محاولة.",
  },
  res_help_feature: {
    en: "Request a Feature",
    ru: "Предложить функцию",
    fr: "Proposer une fonctionnalité",
    ar: "اقتراح ميزة",
  },
  res_help_feature_sub: {
    en: "Suggest new ideas",
    ru: "Поделитесь идеей",
    fr: "Partagez vos idées",
    ar: "شاركنا فكرتك",
  },
  res_help_feature_body: {
    en: "Describe the problem you are trying to solve rather than the control you imagine — the task usually suggests a better solution than the first interface that comes to mind. Mention how often you hit it and what you do today as a workaround.",
    ru: "Опишите задачу, которую хотите решить, а не конкретный элемент интерфейса — по задаче обычно находится решение лучше первого пришедшего в голову. Укажите, как часто вы с этим сталкиваетесь и что делаете сейчас в обход.",
    fr: "Décrivez le problème que vous cherchez à résoudre plutôt que le bouton que vous imaginez : la tâche suggère souvent une meilleure solution que la première interface qui vient à l'esprit. Précisez la fréquence à laquelle vous la rencontrez et votre contournement actuel.",
    ar: "صف المشكلة التي تريد حلّها بدل العنصر الذي تتخيّله؛ فالمهمة نفسها كثيرًا ما توحي بحلّ أفضل من أول واجهة تخطر بالبال. واذكر كم مرة تواجهها وما الحل البديل الذي تستخدمه الآن.",
  },
  /* ---------- Страница Image Color Extractor ---------- */
  imgx_title_plain: {
    en: "Image",
    ru: "Изображение",
    fr: "Image",
    ar: "الصورة",
  },
  imgx_title_grad: {
    en: "Color Extractor",
    ru: "Извлечение цвета",
    fr: "Extracteur de couleurs",
    ar: "مستخرج الألوان",
  },
  imgx_subtitle: {
    en: "Upload an image and extract colors. Click any color to view and copy its values.",
    ru: "Загрузите изображение и извлеките цвета. Нажмите на любой цвет, чтобы посмотреть и скопировать его значения.",
    fr: "Importez une image et extrayez ses couleurs. Cliquez sur une couleur pour voir et copier ses valeurs.",
    ar: "ارفع صورة واستخرج ألوانها. انقر أي لون لعرض قيمه ونسخها.",
  },
  imgx_upload_another: {
    en: "Upload Another",
    ru: "Загрузить другое",
    fr: "Importer une autre",
    ar: "رفع صورة أخرى",
  },
  imgx_export_palette: {
    en: "Export Palette",
    ru: "Экспорт палитры",
    fr: "Exporter la palette",
    ar: "تصدير اللوحة",
  },
  imgx_clear_all: {
    en: "Clear all",
    ru: "Очистить всё",
    fr: "Tout effacer",
    ar: "مسح الكل",
  },
  imgx_saved_empty: {
    en: "No saved colors yet.",
    ru: "Пока нет сохранённых цветов.",
    fr: "Aucune couleur enregistrée pour le moment.",
    ar: "لا توجد ألوان محفوظة بعد.",
  },
  imgx_export_json: {
    en: "Export as JSON",
    ru: "Экспорт в JSON",
    fr: "Exporter en JSON",
    ar: "تصدير بصيغة JSON",
  },
  imgx_export_css: {
    en: "Copy as CSS Variables",
    ru: "Скопировать как CSS-переменные",
    fr: "Copier en variables CSS",
    ar: "نسخ كمتغيرات CSS",
  },
  imgx_panel1_title: {
    en: "Upload Image",
    ru: "Загрузка изображения",
    fr: "Importer une image",
    ar: "رفع صورة",
  },
  imgx_panel1_sub: {
    en: "Upload any image to extract its colors",
    ru: "Загрузите изображение, чтобы извлечь его цвета",
    fr: "Importez une image pour en extraire les couleurs",
    ar: "ارفع أي صورة لاستخراج ألوانها",
  },
  imgx_drop_title: {
    en: "Click to upload or drag and drop",
    ru: "Нажмите, чтобы загрузить, или перетащите файл",
    fr: "Cliquez pour importer ou glissez-déposez",
    ar: "انقر للرفع أو اسحب الصورة وأفلتها",
  },
  imgx_drop_hint: {
    en: "PNG, JPG, WEBP up to 10MB",
    ru: "PNG, JPG, WEBP до 10 МБ",
    fr: "PNG, JPG, WEBP jusqu'à 10 Mo",
    ar: "PNG وJPG وWEBP حتى 10 ميجابايت",
  },
  imgx_remove_image_title: {
    en: "Remove image",
    ru: "Удалить изображение",
    fr: "Supprimer l'image",
    ar: "إزالة الصورة",
  },
  imgx_loaded: {
    en: "Image loaded",
    ru: "Изображение загружено",
    fr: "Image chargée",
    ar: "تم تحميل الصورة",
  },
  imgx_upload_again: {
    en: "Upload Another Image",
    ru: "Загрузить другое изображение",
    fr: "Importer une autre image",
    ar: "رفع صورة أخرى",
  },
  imgx_info_title: {
    en: "Image Info",
    ru: "Информация об изображении",
    fr: "Infos sur l'image",
    ar: "معلومات الصورة",
  },
  imgx_info_format: {
    en: "Format",
    ru: "Формат",
    fr: "Format",
    ar: "الصيغة",
  },
  imgx_info_dimensions: {
    en: "Dimensions",
    ru: "Размер",
    fr: "Dimensions",
    ar: "الأبعاد",
  },
  imgx_info_size: {
    en: "File Size",
    ru: "Размер файла",
    fr: "Taille du fichier",
    ar: "حجم الملف",
  },
  imgx_info_space: {
    en: "Color Space",
    ru: "Цветовое пространство",
    fr: "Espace colorimétrique",
    ar: "فضاء الألوان",
  },
  imgx_info_total: {
    en: "Total Colors",
    ru: "Всего цветов",
    fr: "Couleurs totales",
    ar: "إجمالي الألوان",
  },
  imgx_optimized: {
    en: "(optimized)",
    ru: "(оптимизировано)",
    fr: "(optimisé)",
    ar: "(مُحسَّن)",
  },
  imgx_panel2_title: {
    en: "Extracted Colors",
    ru: "Извлечённые цвета",
    fr: "Couleurs extraites",
    ar: "الألوان المستخرجة",
  },
  imgx_panel2_sub: {
    en: "{n} dominant colors extracted from your image",
    ru: "{n} доминирующих цветов извлечено из изображения",
    fr: "{n} couleurs dominantes extraites de votre image",
    ar: "تم استخراج {n} لونًا سائدًا من صورتك",
  },
  imgx_panel2_sub_empty: {
    en: "Upload an image to get started",
    ru: "Загрузите изображение, чтобы начать",
    fr: "Importez une image pour commencer",
    ar: "ارفع صورة للبدء",
  },
  imgx_colors_word: {
    en: "Colors",
    ru: "цветов",
    fr: "couleurs",
    ar: "لون",
  },
  imgx_sort_vibrance: {
    en: "Sort by Vibrance",
    ru: "По насыщенности",
    fr: "Trier par intensité",
    ar: "الترتيب حسب الحيوية",
  },
  imgx_sort_dominance: {
    en: "Sort by Dominance",
    ru: "По доминированию",
    fr: "Trier par dominance",
    ar: "الترتيب حسب الهيمنة",
  },
  imgx_sort_lightness: {
    en: "Sort by Lightness",
    ru: "По светлоте",
    fr: "Trier par luminosité",
    ar: "الترتيب حسب الإضاءة",
  },
  imgx_sort_hue: {
    en: "Sort by Hue",
    ru: "По тону",
    fr: "Trier par teinte",
    ar: "الترتيب حسب درجة اللون",
  },
  imgx_empty_title: {
    en: "No image yet",
    ru: "Пока нет изображения",
    fr: "Aucune image",
    ar: "لا توجد صورة بعد",
  },
  imgx_empty_body: {
    en: "Upload a photo to extract its dominant colors.",
    ru: "Загрузите фото, чтобы извлечь его доминирующие цвета.",
    fr: "Importez une photo pour en extraire les couleurs dominantes.",
    ar: "ارفع صورة لاستخراج ألوانها السائدة.",
  },
  imgx_strip_caption: {
    en: "Click any color above or on the image to view its details and code.",
    ru: "Нажмите на цвет выше или на изображении, чтобы увидеть его детали и код.",
    fr: "Cliquez sur une couleur ci-dessus ou sur l'image pour voir ses détails et son code.",
    ar: "انقر أي لون أعلاه أو على الصورة لعرض تفاصيله وكوده.",
  },
  imgx_panel3_title: {
    en: "Color Details",
    ru: "Детали цвета",
    fr: "Détails de la couleur",
    ar: "تفاصيل اللون",
  },
  imgx_panel3_sub: {
    en: "Click a color to view all formats and values",
    ru: "Нажмите на цвет, чтобы увидеть все форматы и значения",
    fr: "Cliquez sur une couleur pour voir tous ses formats et valeurs",
    ar: "انقر لونًا لعرض كل صيغه وقيمه",
  },
  imgx_panel3_empty: {
    en: "Select a color from the palette to see its values here.",
    ru: "Выберите цвет из палитры, чтобы увидеть его значения здесь.",
    fr: "Sélectionnez une couleur dans la palette pour voir ses valeurs ici.",
    ar: "اختر لونًا من اللوحة لعرض قيمه هنا.",
  },
  imgx_formats_title: {
    en: "Color Formats",
    ru: "Форматы цвета",
    fr: "Formats de couleur",
    ar: "صيغ اللون",
  },
  imgx_color_label: {
    en: "Color",
    ru: "Цвет",
    fr: "Couleur",
    ar: "لون",
  },
  imgx_add_saved: {
    en: "Add to Saved",
    ru: "Добавить в сохранённые",
    fr: "Ajouter aux enregistrés",
    ar: "إضافة إلى المحفوظات",
  },
  imgx_remove_saved: {
    en: "Remove from Saved",
    ru: "Убрать из сохранённых",
    fr: "Retirer des enregistrés",
    ar: "إزالة من المحفوظات",
  },
  imgx_saved_added: {
    en: "Color saved",
    ru: "Цвет сохранён",
    fr: "Couleur enregistrée",
    ar: "تم حفظ اللون",
  },
  imgx_saved_removed: {
    en: "Color removed",
    ru: "Цвет удалён",
    fr: "Couleur retirée",
    ar: "تمت إزالة اللون",
  },
  imgx_exported_json: {
    en: "Palette exported",
    ru: "Палитра экспортирована",
    fr: "Palette exportée",
    ar: "تم تصدير اللوحة",
  },
  imgx_exported_css: {
    en: "CSS variables copied",
    ru: "CSS-переменные скопированы",
    fr: "Variables CSS copiées",
    ar: "تم نسخ متغيرات CSS",
  },
  imgx_invalid_file: {
    en: "Please upload an image file",
    ru: "Загрузите файл изображения",
    fr: "Veuillez importer un fichier image",
    ar: "يرجى رفع ملف صورة",
  },
  imgx_file_too_large: {
    en: "Image is larger than 10MB",
    ru: "Изображение больше 10 МБ",
    fr: "L'image dépasse 10 Mo",
    ar: "حجم الصورة يتجاوز 10 ميجابايت",
  },
  imgx_extract_failed: {
    en: "Couldn't analyze this image",
    ru: "Не удалось проанализировать изображение",
    fr: "Impossible d'analyser cette image",
    ar: "تعذّر تحليل هذه الصورة",
  },
  imgx_image_removed: {
    en: "Image removed",
    ru: "Изображение удалено",
    fr: "Image supprimée",
    ar: "تمت إزالة الصورة",
  },
  toast_use_image_page: {
    en: "Drop images on the Image page to extract colors",
    ru: "Перетащите изображение на страницу «Изображение», чтобы извлечь цвета",
    fr: "Déposez les images sur la page Image pour en extraire les couleurs",
    ar: "أفلت الصور في صفحة «الصورة» لاستخراج ألوانها",
  },
};

/* ---------- Логика переключения ---------- */

const LANG_STORAGE_KEY = "cp-lang";
const THEME_STORAGE_KEY = "cp-theme";

function getLang() {
  const saved = localStorage.getItem(LANG_STORAGE_KEY);
  if (saved && LANGUAGES.some((l) => l.code === saved)) return saved;
  return "ru";
}

function t(key) {
  const lang = getLang();
  const entry = I18N[key];
  if (!entry) return key;
  return entry[lang] || entry.en || key;
}

function setLang(code) {
  localStorage.setItem(LANG_STORAGE_KEY, code);
  document.documentElement.lang = code;
  document.documentElement.dir = RTL_LANGS.has(code) ? "rtl" : "ltr";
  applyI18n();
}

function applyI18n() {
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-title]").forEach((el) => {
    const text = t(el.getAttribute("data-i18n-title"));
    el.setAttribute("title", text);
    if (el.hasAttribute("aria-label")) el.setAttribute("aria-label", text);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    el.setAttribute("placeholder", t(el.getAttribute("data-i18n-placeholder")));
  });
}

/* ---------- Тема (сохранение выбора; сами стили светлой темы не входят) ---------- */

function getTheme() {
  const saved = localStorage.getItem(THEME_STORAGE_KEY);
  return saved === "light" ? "light" : "dark";
}

function setTheme(mode) {
  localStorage.setItem(THEME_STORAGE_KEY, mode);
  document.documentElement.setAttribute("data-theme", mode);
  document.body.classList.toggle("light-preview", mode === "light");
}
